
[[Static-UndeclaredFunction]]
# UndeclaredFunction
:concept: Static/UndeclaredFunction

.Synopsis
A function is called that has not been declared.

.Syntax

.Types

.Function
       
.Usage

.Description
All functions, constructors and variables have to be declared before they can be used.
This error is generated when this rule is violated.

Remedies for functions:

*  Declare the function.
*  Declare the function as constructor of an (existing or new) [Rascal:AlgebraicDataType].
*  Import a module that declares the function (Did you import all necessary library modules?)

Remedies for variables:

*  Declare the variable.

.Examples
Calling the undeclared function `triple` gives an error:
[source,rascal-shell-error]
----
rascal>triple(5)
[error] Name triple is not in scope
----
We can remedy this by declaring the function:
[source,rascal-shell-error]
----
rascal>int triple(int n) = 3 * n;
ok
rascal>triple(5)
int: 15
----

Calling the library function `size` gives an error if the proper library (in this case: `List`) is not imported
[source,rascal-shell-error]
----
rascal>size([20, 1, 77]);
[error] Name size is not in scope
----
The solution is:
[source,rascal-shell]
----
rascal>import List;
ok
rascal>size([20, 1, 77]);
int: 3
----
Another solution is to import the complete Rascal library at once:
[source,rascal-shell]
----
rascal>import Prelude;
ok
rascal>size([20, 1, 77]);
int: 3
----

Using an undeclared variable gives an error:
[source,rascal-shell-error]
----
rascal>n + 1;
[error] Name n is not in scope
----
A variable is introduced by just assigning to it (with or without its expected type):
[source,rascal-shell]
----
rascal>n = 3;
int: 3
rascal>n + 1;
int: 4
----
Or equivalenty (with an expected type):
[source,rascal-shell]
----
rascal>int n = 3;
int: 3
rascal>n + 1;
int: 4
----

.Benefits

.Pitfalls


:leveloffset: +1

:leveloffset: -1