
[[Static-UnsupportedOperation]]
# UnsupportedOperation
:concept: Static/UnsupportedOperation

.Synopsis
Attempt to apply a operation to a value for which the operation is not defined.

.Syntax

.Types

.Function
       
.Usage

.Description
This error is generated when an unsupported operation is applied to (a combination of) values.
There can be many causes for this as illustrated below.

Remedies: 

*  Change the operation to another operations that is supported on the given values.
*  Change the values so that the operation can be applied to them.
*  Rewrite the expression compleye to get the effect you intended.

.Examples
[source,rascal-shell-error]
----
rascal>L = [1,2,3];
list[int]: [1,2,3]
----
Division is not supported on lists:
[source,rascal-shell-error]
----
rascal>[1, 2, 3] / 4;
[error] Division not defined on list[int] and int IN '[1, 2, 3] / 4'
----
Combined multiplication and assignment is not supported either:
[source,rascal-shell-error]
----
rascal>L *= 3;
[error] Product not defined on list[int] and int IN 'L *= 3;'
----
Taking the time from a date-only value is not supported:
[source,rascal-shell-error]
----
rascal>$2010-07-15.justTime;
----
Calling an integer as a function is not supported:
[source,rascal-shell-error]
----
rascal>17(3, "abc");
[error] Cannot use type int in calls IN '17(3, "abc")'
----

.Benefits

.Pitfalls


:leveloffset: +1

:leveloffset: -1