
[[Prelude-List]]


[[Prelude-List]]
# List
:concept: Prelude/List
.Usage
`import List;`


.Synopsis
Library functions for lists.

.Description

For operators on lists see link:{RascalLang}#Values-List[List] in the Rascal Language Reference.

The following functions are available for lists:


[[List-concat]]
## concat

.Function 
`list[&T] concat(list[list[&T]] xxs)`

.Synopsis
Concatenate a list of lists.

.Examples
[source,rascal-shell]
----
rascal>import List;
ok
rascal>concat([]);
list[void]: []
rascal>concat([[]]);
list[void]: []
rascal>concat([[1]]);
list[int]: [1]
rascal>concat([[1],[],[2,3]]);
list[int]: [1,2,3]
rascal>concat([[1,2],[3],[4,5],[]]);
list[int]: [1,2,3,4,5]
----

[[List-delete]]
## delete

.Function 
`list[&T] delete(list[&T] lst, int n)`

.Synopsis
Delete an element from a list.

.Description
Delete the `n`-th element from a list. A new list without the `n`-th element is returned as result.
The `IndexOutOfBounds` exception is thrown when n is not a valid index.

.Examples
[source,rascal-shell]
----
rascal>import List;
ok
rascal>delete([1, 2, 3], 1);
list[int]: [1,3]
rascal>delete(["zebra", "elephant", "snake", "owl"], 2);
list[str]: ["zebra","elephant","owl"]
----

[[List-distribution]]
## distribution

.Function 
`map[&T element, int occurs] distribution(list[&T] lst)`

.Synopsis
Get the distribution of the elements of the list. That
is how often does each element occur in the list? 

.Examples
[source,rascal-shell]
----
rascal>import List;
ok
rascal>distribution([4,4,4,3,1,2,1,1,3,4]);
map[int, int]: (1:3,3:2,2:1,4:4)
----

[[List-drop]]
## drop

.Function 
`list[&T] drop(int n, list[&T] lst)`

.Synopsis
Drop elements from the head of a list.

.Description
Drop `n` elements (or `size(lst)` elements if `size(lst) < n`) from the head of `lst`.
See <<List-take>> to get elements from the head of a list].

.Examples
[source,rascal-shell]
----
rascal>import List;
ok
rascal>drop(2, [5, 1, 7, 3]);
list[int]: [7,3]
rascal>drop(10, [5, 1, 7, 3]);
list[void]: []
rascal>drop(2, ["zebra", "elephant", "snake", "owl"]);
list[str]: ["snake","owl"]
----

[[List-dup]]
## dup

.Function 
`list[&T] dup(list[&T] lst)`

.Synopsis
Remove multiple occurrences of elements in a list. The first occurrence remains.

.Examples
[source,rascal-shell]
----
rascal>import List;
ok
rascal>dup([3, 1, 5, 3, 1, 7, 1, 2]);
list[int]: [3,1,5,7,2]
----

[[List-elementAt]]
## elementAt

.Function 
`&T elementAt(list[&T] lst, int index)`



[[List-getOneFrom]]
## getOneFrom

.Function 
`&T getOneFrom(list[&T] lst)`

.Synopsis
Pick a random element from a list.

.Description
Get an arbitrary element from a list. See <<List-takeOneFrom>> for a function that also removes the selected element.

.Examples
[source,rascal-shell]
----
rascal>import List;
ok
rascal>getOneFrom(["zebra", "elephant", "snake", "owl"]);
str: "zebra"
rascal>getOneFrom(["zebra", "elephant", "snake", "owl"]);
str: "elephant"
rascal>getOneFrom(["zebra", "elephant", "snake", "owl"]);
str: "zebra"
----

[[List-getFirstFrom]]
## getFirstFrom

.Function 
`&T getFirstFrom(list[&T] lst)`

.Synopsis
Pick first element from a list.

.Description
Get the first element from a list. As opposed to <<List-getOneFrom>> this function always returns the same (first) list element.

[[List-head]]
## head

.Function 
* `&T head(list[&T] lst) throws EmptyList`
          * `list[&T] head(list[&T] lst, int n) throws IndexOutOfBounds`
          

.Synopsis
Get the first element(s) from a list.

.Description

* Returns the first element of a list or throws `EmptyList` when the list is empty. 
  This is identical to <<top>>.
* Returns the first `n` elements of a list or throws `IndexOutOfBounds` when the list is too short. 
  This is similar to <<take>>.

.Examples
[source,rascal-shell-error]
----
rascal>import List;
ok
----
Get the first element:
[source,rascal-shell-error]
----
rascal>head([1, 2, 3]);
int: 1
rascal>head(["zebra", "elephant", "snake", "owl"]);
str: "zebra"
----
An exception is thrown when taking the head of an empty list:
[source,rascal-shell-error]
----
rascal>head([]);
EmptyList()
Call stack (most recent first):
	head([], {}) at |std:///List.rsc|(3617,1019,<156,0>,<195,51>)
	main([]) at |test-modules:///ConsoleInput.rsc|(49,8,<4,15>,<4,23>)

ok
----
Get the first n elements:
[source,rascal-shell-error]
----
rascal>head([1, 2, 3, 4], 2);
list[int]: [1,2]
rascal>head(["zebra", "elephant", "snake", "owl"], 2);
list[str]: ["zebra","elephant"]
----
An exception is thrown when the second argument exceeds the length of the list:
[source,rascal-shell-error]
----
rascal>head([1, 2, 3, 5], 5);
IndexOutOfBounds(4)
Call stack (most recent first):
	head([1,2,3,5], 5, {}) at |std:///List.rsc|(4676,113,<198,0>,<199,71>)
	main([]) at |test-modules:///ConsoleInput.rsc|(49,21,<4,15>,<4,36>)

ok
----

[[List-headTail]]
## headTail

.Function 
`tuple[&T, list[&T]] headTail(list[&T] lst) throws EmptyList`

.Synopsis
Split a list in a head and a tail.

.Description
This function is identical to <<List-pop>>.

.Examples
[source,rascal-shell]
----
rascal>import List;
ok
rascal>headTail([3, 1, 4, 5]);
tuple[int,list[int]]: <3,[1,4,5]>
rascal>pop([3, 1, 4, 5]);
tuple[int,list[int]]: <3,[1,4,5]>
rascal>headTail(["zebra", "elephant", "snake", "owl"]);
tuple[str,list[str]]: <"zebra",["elephant","snake","owl"]>
----

[[List-index]]
## index

.Function 
`list[int] index(list[&T] lst)`

.Synopsis
A list of legal index values of a list.

.Description
Returns a list of all legal index values for a given list `lst`.

.Examples
[source,rascal-shell]
----
rascal>import List;
ok
rascal>index([1, 3, 5]);
list[int]: [0,1,2]
rascal>index(["zebra", "elephant", "snake", "owl"]);
list[int]: [0,1,2,3]
----

.Benefits
This function is useful in link:{RascalLang}#Statements-For[for] loops over lists.

[[List-indexOf]]
## indexOf

.Function 
`int indexOf(list[&T] lst, &T elt)`

.Synopsis
Index of first occurrence of an element in a list.

.Description
Return index of first occurrence of `elt` in `lst`, or `-1` if `elt` is not found.
Also see <<List-lastIndexOf>>.

.Examples
[source,rascal-shell]
----
rascal>import List;
ok
rascal>indexOf([3, 1, 4, 5], 4);
int: 2
rascal>indexOf([3, 1, 4, 5], 7);
int: -1
rascal>indexOf(["zebra", "elephant", "snake", "owl"], "snake");
int: 2
rascal>indexOf(["zebra", "elephant", "snake", "owl"], "eagle");
int: -1
----

[[List-insertAt]]
## insertAt

.Function 
`list[&T] insertAt(list[&T] lst, int n, &T elm) throws IndexOutOfBounds`

.Synopsis
Insert an element at a specific position in a list.

.Description
Returns a new list with the value of `elm` inserted at index position `n` of the old list.

.Examples
[source,rascal-shell-error]
----
rascal>import List;
ok
rascal>insertAt([1,2,3], 1, 5);
list[int]: [1,5,2,3]
rascal>insertAt(["zebra", "elephant", "snake", "owl"], 2, "eagle");
list[str]: ["zebra","elephant","eagle","snake","owl"]
----
An exception is thrown when the index position is outside the list:
[source,rascal-shell-error]
----
rascal>insertAt([1,2,3], 10, 5);
IndexOutOfBounds(10)
Call stack (most recent first):
	insertAt([1,2,3], 10, 5, {}) at |std:///List.rsc|(6149,588,<267,0>,<287,83>)
	main([]) at |test-modules:///ConsoleInput.rsc|(49,24,<4,15>,<4,39>)

ok
----

[[List-intercalate]]
## intercalate

.Function 
`str intercalate(str sep, list[value] l)`

.Synopsis
Join a list of values into a string separated by a separator.

.Examples
[source,rascal-shell]
----
rascal>import List;
ok
rascal>intercalate("/", [3]);
str: "3"
rascal>intercalate("/", [3, 1, 4, 5]);
str: "3/1/4/5"
rascal>intercalate(", ", [3, 1, 4, 5]);
str: "3, 1, 4, 5"
rascal>intercalate(", ", ["zebra", "elephant", "snake", "owl"]);
str: "zebra, elephant, snake, owl"
----

[[List-intersperse]]
## intersperse

.Function 
`list[&T] intersperse(&T sep, list[&T] xs)`

.Synopsis
Intersperses a list of values with a separator.

.Examples
[source,rascal-shell]
----
rascal>import List;
ok
rascal>intersperse(", ", ["a","b","c"]);
list[str]: ["a",", ","b",", ","c"]
rascal>intersperse(0, [1, 2, 3]);
list[int]: [1,0,2,0,3]
rascal>intersperse(1, []);
list[void]: []
rascal>intersperse([], [1]);
list[int]: [1]
----

[[List-isEmpty]]
## isEmpty

.Function 
`bool isEmpty(list[&T] lst)`

.Synopsis
Test whether a list is empty.

.Description
Returns `true` when a list is empty and `false` otherwise.

.Examples
[source,rascal-shell]
----
rascal>import List;
ok
rascal>isEmpty([]);
bool: true
rascal>isEmpty([1, 2, 3]);
bool: false
----

[[List-last]]
## last

.Function 
`&T last(list[&T] lst) throws EmptyList`

.Synopsis
Return the last element of a list, if any.

.Description
Also see <<List-tail>> that returns a list of one or more of the last elements of a list.

.Examples
[source,rascal-shell]
----
rascal>import List;
ok
rascal>last([1]);
int: 1
rascal>last([3, 1, 4, 5]);
int: 5
rascal>last(["zebra", "elephant", "snake", "owl"]);
str: "owl"
rascal>tail([3, 1, 4, 5]);
list[int]: [1,4,5]
----

[[List-lastIndexOf]]
## lastIndexOf

.Function 
`int lastIndexOf(list[&T] lst, &T elt)`

.Synopsis
Return index of last occurrence of elt in lst, or -1 if elt is not found.

.Description
Also see <<List-indexOf>>.

.Examples
[source,rascal-shell]
----
rascal>import List;
ok
rascal>lastIndexOf([3, 1, 4, 5, 4], 4);
int: 4
rascal>lastIndexOf([3, 1, 4, 5, 4], 7);
int: -1
rascal>lastIndexOf(["zebra", "owl", "elephant", "snake", "owl"], "owl");
int: 4
----

[[List-mapper]]
## mapper

.Function 
`list[&U] mapper(list[&T] lst, &U (&T) fn)`

.Synopsis
Apply a function to all list elements and return list of results.

.Description
Apply a function `fn` to each element of `lst` and return the list of results.

.Examples
[source,rascal-shell]
----
rascal>import List;
ok
rascal>int incr(int x) { return x + 1; }
ok
rascal>mapper([1, 2, 3, 4], incr);
list[int]: [2,3,4,5]
----

[[List-max]]
## max

.Function 
`&T max(list[&T] lst) throws EmptyList`

.Synopsis
Determine the largest element in a list.

.Examples
[source,rascal-shell]
----
rascal>import List;
ok
rascal>max([1, 3, 5, 2, 4]);
int: 5
rascal>max(["zebra", "elephant", "snake", "owl"]);
str: "zebra"
----

[[List-merge]]
## merge

.Function 
* `list[&T] merge(list[&T] left, list[&T] right)`
          * `list[&T] merge(list[&T] left, list[&T] right, bool (&T a, &T b) lessOrEqual)`
          

.Synopsis
Merge the elements of two sorted lists into one list.

.Description
Merge the elements of two sorted lists into one list using the built-in ordering between values.
Optional, a comparison function `lessOrEqual` may be given for a user-defined ordering between values.


.Examples

[source,rascal-shell]
----
rascal>import List;
ok
rascal>merge([1, 3, 5], [2, 7, 9, 15]);
list[int]: [1,2,3,5,7,9,15]
rascal>merge(["ape", "elephant", "owl", "snale", "zebra"], ["apple", "berry", "orange", "pineapple"]);
list[str]: ["ape","apple","berry","elephant","orange","owl","pineapple","snale","zebra"]
----
Merge two lists of strings and use their length as ordering:
[source,rascal-shell]
----
rascal>import String;
ok
rascal>merge(["ape", "owl", "snale", "zebra", "elephant"], ["apple", "berry", "orange", "pineapple"], bool(str x, str y){ return size(x) <= size(y); });
list[str]: ["ape","owl","snale","zebra","apple","berry","orange","elephant","pineapple"]
----

[[List-min]]
## min

.Function 
`&T min(list[&T] lst)`

.Synopsis
Determine the smallest element in a list.

.Examples
[source,rascal-shell]
----
rascal>import List;
ok
rascal>min([1, 3, 5, 2, 4]);
int: 1
rascal>min(["zebra", "elephant", "snake", "owl"]);
str: "elephant"
----

[[List-mix]]
## mix

.Function 
`list[&T] mix(list[&T] l, list[&T] r)`

.Synopsis
Mix the elements of two lists.

.Description
Let n be the minimum of the length of the two lists `l` and `r`.
`mix` returns a list in which the first `n` elements are taken alternately from the left and the right list,
followed by the remaining elements of the longest list.

.Examples
[source,rascal-shell]
----
rascal>import List;
ok
rascal>mix([3, 1, 7, 5, 9], [15, 25, 35]);
list[int]: [3,15,1,25,7,35,5,9]
rascal>mix([3, 1, 7], [15, 25, 35, 45, 55]);
list[int]: [3,15,1,25,7,35,45,55]
rascal>mix([3, 1, 7], ["elephant", "snake"]);
list[value]: [3,"elephant",1,"snake",7]
----

[[List-permutations]]
## permutations

.Function 
`set[list[&T]] permutations(list[&T] lst)`

.Synopsis
Compute all permutations of a list.

.Examples
[source,rascal-shell]
----
rascal>import List;
ok
rascal>permutations([1,2,3]);
set[list[int]]: {
  [3,2,1],
  [1,2,3],
  [2,1,3],
  [1,3,2],
  [2,3,1],
  [3,1,2]
}
----

[[List-permutationsBag]]
## permutationsBag

.Function 
`set[list[&T]] permutationsBag(map[&T element, int occurs] b)`



[[List-pop]]
## pop

.Function 
`tuple[&T, list[&T]] pop(list[&T] lst) throws EmptyList`

.Synopsis
Pop top element from list, return a tuple.
.Description
This function is identical to <<headTail>>.
Also see <<List-push>> and <<List-top>>.

.Examples
[source,rascal-shell]
----
rascal>import List;
ok
rascal>pop([3, 1, 4, 5]);
tuple[int,list[int]]: <3,[1,4,5]>
rascal>headTail([3, 1, 4, 5]);
tuple[int,list[int]]: <3,[1,4,5]>
rascal>pop(["zebra", "elephant", "snake", "owl"]);
tuple[str,list[str]]: <"zebra",["elephant","snake","owl"]>
----

[[List-prefix]]
## prefix

.Function 
`list[&T] prefix(list[&T] lst)`

.Synopsis
Return all but the last element of a list.

.Examples
[source,rascal-shell]
----
rascal>import List;
ok
rascal>prefix([3, 1, 4, 5]);
list[int]: [3,1,4]
rascal>prefix([]);
list[void]: []
rascal>prefix(["zebra", "elephant", "snake", "owl"]);
list[str]: ["zebra","elephant","snake"]
----

[[List-push]]
## push

.Function 
`list[&T] push(&T elem, list[&T] lst)`

.Synopsis
Push an element in front of a list.

.Description
Also see <<List-pop>> and <<List-top>>.

.Examples
[source,rascal-shell]
----
rascal>import List;
ok
rascal>push(7, [3, 1, 4, 5]);
list[int]: [7,3,1,4,5]
rascal>push("eagle", ["zebra", "elephant", "snake", "owl"]);
list[str]: ["eagle","zebra","elephant","snake","owl"]
----

[[List-reducer]]
## reducer

.Function 
`&T reducer(list[&T] lst, &T (&T, &T) fn, &T unit)`

.Synopsis
Apply a function to successive elements of list and combine the results (__deprecated__).

.Description
Apply the function `fn` to successive elements of list `lst` starting with `unit`.

.Examples
[source,rascal-shell]
----
rascal>import List;
ok
rascal>int add(int x, int y) { return x + y; }
ok
rascal>reducer([10, 20, 30, 40], add, 0); 
int: 100
----

.Benefits

.Pitfalls
WARNING:
This function is *deprecated*, use a link:{rascalLang}#Expressions-Reducer[reducer] instead.

[[List-remove]]
## remove

.Function 
`list[&T] remove(list[&T] lst, int indexToDelete)`



[[List-removeFromBag]]
## removeFromBag

.Function 
* `map[&T element, int occurs] removeFromBag(map[&T element, int occurs] b, &T el)`
          * `map[&T element, int occurs] removeFromBag(map[&T element, int occurs] b, &T el, int nr)`
          



[[List-reverse]]
## reverse

.Function 
`list[&T] reverse(list[&T] lst)`

.Synopsis
Reverse a list.

.Description
Returns a list with the elements of `lst` in reverse order.

.Examples
[source,rascal-shell]
----
rascal>import List;
ok
rascal>reverse([1,4,2,3]);
list[int]: [3,2,4,1]
rascal>reverse(["zebra", "elephant", "snake", "owl"]);
list[str]: ["owl","snake","elephant","zebra"]
----

[[List-size]]
## size

.Function 
`int size(list[&T] lst)`

.Synopsis
Determine the number of elements in a list.

.Examples
[source,rascal-shell]
----
rascal>import List;
ok
rascal>size([20, 10, 30]);
int: 3
rascal>size(["zebra", "elephant", "snake", "owl"]);
int: 4
----

[[List-slice]]
## slice

.Function 
`list[&T] slice(list[&T] lst, int begin, int len)`

.Synopsis
Compute a sublist of a list.

.Description
Returns a sublist of `lst` from index `start` of length `len`.

NOTE: In most cases it is better to use the built-in link:{RascalLang}#List-Slice[slice] notation,
see the example below.

.Examples
[source,rascal-shell]
----
rascal>import List;
ok
rascal>slice([10, 20, 30, 40, 50, 60], 2, 3);
list[int]: [30,40,50]
rascal>slice(["zebra", "elephant", "snake", "owl"], 1, 2);
list[str]: ["elephant","snake"]
----
Here are the equivalent expressions using the slice notation:
[source,rascal-shell]
----
rascal>[10, 20, 30, 40, 50, 60][2 .. 5];
list[int]: [30,40,50]
rascal>["zebra", "elephant", "snake", "owl"][1 .. 3];
list[str]: ["elephant","snake"]
----
WARNING: In the slice notation the upper bound is exclusive.

[[List-sort]]
## sort

.Function 
* `list[&T] sort(list[&T] lst)`
          * `list[&T] sort(list[&T] l, bool (&T a, &T b) less)`
          

.Synopsis
Sort the elements of a list.

.Description
Sort the elements of a list:

*  Use the built-in ordering on values to compare list elements.
*  Give an additional `lessThan` function that will be used to compare elements.

.Examples
[source,rascal-shell]
----
rascal>import List;
ok
rascal>import String;
ok
rascal>sort([10, 4, -2, 11, 100, 5]);
list[int]: [-2,4,5,10,11,100]
rascal>fruits = ["mango", "strawberry", "pear", "pineapple", "banana", "grape", "kiwi"];
list[str]: ["mango","strawberry","pear","pineapple","banana","grape","kiwi"]
rascal>sort(fruits);
list[str]: ["banana","grape","kiwi","mango","pear","pineapple","strawberry"]
rascal>sort(fruits, bool(str a, str b){ return size(a) > size(b); });
list[str]: ["strawberry","pineapple","banana","grape","mango","kiwi","pear"]
----

[[List-shuffle]]
## shuffle

.Function 
* `list[&T] shuffle(list[&T] l)`
          * `list[&T] shuffle(list[&T] l, int seed)`
          

.Synopsis
Shuffle a list.

.Description
Returns a random (unbiased) shuffled list.

.Examples
[source,rascal-shell]
----
rascal>import List;
ok
rascal>shuffle([1,4,2,3]);
list[int]: [4,1,2,3]
rascal>shuffle(["zebra", "elephant", "snake", "owl"]);
list[str]: ["zebra","owl","elephant","snake"]
----

[[List-split]]
## split

.Function 
`tuple[list[&T],list[&T]] split(list[&T] l)`

.Synopsis
Split a list into two halves.

.Examples
[source,rascal-shell]
----
rascal>import List;
ok
rascal>split([3, 1, 4, 5, 7]);
tuple[list[int],list[int]]: <[3,1],[4,5,7]>
rascal>split(["zebra", "elephant", "snake", "owl"]);
tuple[list[str],list[str]]: <["zebra","elephant"],["snake","owl"]>
----

[[List-sum]]
## sum

.Function 
* `(&T <:num) sum(list[(&T <:num)] _:[])`
          * `default (&T <:num) sum([(&T <: num) hd, *(&T <: num) tl])`
          



[[List-tail]]
## tail

.Function 
* `list[&T] tail(list[&T] lst) throws EmptyList`
          * `list[&T] tail(list[&T] lst, int len) throws IndexOutOfBounds`
          

.Synopsis
Get the tail element(s) from a list.

.Description

*  Return a list consisting of all but the first element of `lst`.
*  Return a list consisting of the last `n` elements of `lst`.

.Examples
[source,rascal-shell-error]
----
----
All but first element:
[source,rascal-shell-error]
----
rascal>import List;
ok
rascal>tail([10,20,30]);
list[int]: [20,30]
----
Try an error case:
[source,rascal-shell-error]
----
rascal>tail([]);
EmptyList()
Call stack (most recent first):
	tail([], {}) at |std:///List.rsc|(17604,725,<766,0>,<801,57>)
	main([]) at |test-modules:///ConsoleInput.rsc|(49,8,<4,15>,<4,23>)

ok
----
Last n elements:
[source,rascal-shell-error]
----
rascal>tail([10, 20, 30, 40, 50, 60], 3);
list[int]: [40,50,60]
----
Try an error case:
[source,rascal-shell-error]
----
rascal>tail([10, 20, 30, 40, 50, 60], 10);
IndexOutOfBounds(4)
Call stack (most recent first):
	tail([10,20,30,40,50,60], 10, {}) at |std:///List.rsc|(18332,115,<803,0>,<804,73>)
	main([]) at |test-modules:///ConsoleInput.rsc|(49,34,<4,15>,<4,49>)

ok
----

[[List-take]]
## take

.Function 
`list[&T] take(int n, list[&T] lst)`

.Synopsis
Get number of elements from the head of a list.

.Description
Get `n` elements (or `size(lst)` elements if `size(lst) < n`) from the head of the list.
See <<List-drop>> to remove elements from the head of a list.

.Examples
[source,rascal-shell]
----
rascal>import List;
ok
rascal>take(2, [3, 1, 4, 5]);
list[int]: [3,1]
rascal>take(6, [3, 1, 4, 5]);
list[int]: [3,1,4,5]
rascal>take(2, ["zebra", "elephant", "snake", "owl"]);
list[str]: ["zebra","elephant"]
----

[[List-takeOneFrom]]
## takeOneFrom

.Function 
`tuple[&T, list[&T]] takeOneFrom(list[&T] lst)`

.Synopsis
Remove an arbitrary element from a list, returns the element and the modified list.

.Description
Select an arbitrary element from `lst`, and return a tuple consisting of:

*  the selected element, and 
*  a new list consisting of all elements of `lst` except the selected element.


See <<List-getOneFrom>> to only selected an element from a list.

.Examples
[source,rascal-shell]
----
rascal>import List;
ok
rascal>takeOneFrom([10,20,30,40,50]);
tuple[int,list[int]]: <40,[10,20,30,50]>
rascal>takeOneFrom([10,20,30,40,50]);
tuple[int,list[int]]: <10,[20,30,40,50]>
rascal>takeOneFrom([10,20,30,40,50]);
tuple[int,list[int]]: <30,[10,20,40,50]>
rascal>takeOneFrom(["zebra", "elephant", "snake", "owl"]);
tuple[str,list[str]]: <"owl",["zebra","elephant","snake"]>
rascal>takeOneFrom(["zebra", "elephant", "snake", "owl"]);
tuple[str,list[str]]: <"elephant",["zebra","snake","owl"]>
rascal>takeOneFrom(["zebra", "elephant", "snake", "owl"]);
tuple[str,list[str]]: <"zebra",["elephant","snake","owl"]>
----

[[List-takeWhile]]
## takeWhile

.Function 
`list[&T] takeWhile(list[&T] lst, bool (&T a) take)`

.Synopsis
Take elements from the front of the list as long as a predicate is true.

.Examples
[source,rascal-shell]
----
rascal>import List;
ok
rascal>bool isEven(int a) = a mod 2 == 0;
ok
rascal>takeWhile([2,4,6,8,1,2,3,4,5],isEven);
list[int]: [2,4,6,8]
----

[[List-toMap]]
## toMap

.Function 
`map[&A,set[&B]] toMap(list[tuple[&A, &B]] lst) throws MultipleKey`

.Synopsis
Convert a list of pairs to a map; first elements are associated with a set of second elements.

.Description
Convert a list of tuples to a map in which the first element of each tuple is 
associated with the set of second elements from all tuples with the same first element. Keys should be unique.

.Examples
[source,rascal-shell]
----
rascal>import List;
ok
rascal>toMap([<1,10>, <1, 11>, <2, 20>, <3, 30>, <3, 31>]);
map[int, set[int]]: (
  1:{10,11},
  3:{31,30},
  2:{20}
)
----

.Pitfalls
`toMap` collects all values in tuples with the same first value in a set.
Contrast this with `toMapUnique` that associates each first tuple value with the second tuple value,
but imposes the constraint that those keys are unique.

[[List-toMapUnique]]
## toMapUnique

.Function 
`map[&A,&B] toMapUnique(list[tuple[&A, &B]] lst) throws MultipleKey`

.Synopsis
Convert a list of tuples to a map; result must be a map.

.Description
Convert a list of tuples to a map; result must be a map.

.Examples
[source,rascal-shell-error]
----
rascal>import List;
ok
rascal>toMapUnique([<1,10>, <2, 20>, <3, 30>]);
map[int, int]: (1:10,3:30,2:20)
----
Let's explore an error case:
[source,rascal-shell-error]
----
rascal>toMapUnique([<1,10>, <1, 11>, <2, 20>, <3, 30>]);
MultipleKey(1)
Call stack (most recent first):
	toMapUnique([<1,10>,<1,11>,<2,20>,<3,30>], {}) at |std:///List.rsc|(20847,667,<893,0>,<916,79>)
	main([]) at |test-modules:///ConsoleInput.rsc|(49,48,<4,15>,<4,63>)

ok
----

.Pitfalls
The keys in a map are unique by definition.
`toMapUnique` throws a `MultipleKey` exception when the list contains more than one tuple with the same first value.

[[List-top]]
## top

.Function 
`&T top(list[&T] lst) throws EmptyList`

.Synopsis
Take the top element of a list.
.Description
This function is identical to <<head>>.
Also see <<List-pop>> and <<List-push>>.

.Examples
[source,rascal-shell]
----
rascal>import List;
ok
rascal>top([3, 1, 4, 5]);
int: 3
rascal>top(["zebra", "elephant", "snake", "owl"]);
str: "zebra"
----

[[List-toRel]]
## toRel

.Function 
`rel[&T,&T] toRel(list[&T] lst)`

.Synopsis
Convert a list to a relation.
.Description
  Convert a list to relation, where each tuple encodes which elements are followed by each other.
  This function will return an empty relation for empty lists and for singleton lists.

.Examples
[source,rascal-shell]
----
rascal>import List;
ok
rascal>toRel([3, 1, 4, 5]);
rel[int,int]: {
  <1,4>,
  <4,5>,
  <3,1>
}
rascal>toRel(["zebra", "elephant", "snake", "owl"]);
rel[str,str]: {
  <"snake","owl">,
  <"zebra","elephant">,
  <"elephant","snake">
}
----

[[List-toSet]]
## toSet

.Function 
`set[&T] toSet(list[&T] lst)`

.Synopsis
Convert a list to a set.

.Description
Convert `lst` to a set.

.Examples
[source,rascal-shell]
----
rascal>import List;
ok
rascal>toSet([10, 20, 30, 40]);
set[int]: {10,40,20,30}
rascal>toSet(["zebra", "elephant", "snake", "owl"]);
set[str]: {"snake","owl","zebra","elephant"}
----
Note that the same can be done using splicing
[source,rascal-shell]
----
rascal>l = [10,20,30,40];
list[int]: [10,20,30,40]
rascal>s = {*l};
set[int]: {10,40,20,30}
----

[[List-toString]]
## toString

.Function 
`str toString(list[&T] lst)`

.Synopsis
Convert a list to a string.

.Description
Convert `lst` to a string.

.Examples
[source,rascal-shell]
----
rascal>import List;
ok
rascal>toString([10, 20, 30]);
str: "[10,20,30]"
rascal>toString(["zebra", "elephant", "snake", "owl"]);
str: "[\"zebra\",\"elephant\",\"snake\",\"owl\"]"
----

[[List-itoString]]
## itoString

.Function 
`str itoString(list[&T] lst)`

.Synopsis
Convert a list to an indented string.

.Description
Convert `lst` to a indented string.

.Examples
[source,rascal-shell]
----
rascal>import List;
ok
rascal>itoString([10, 20, 30]);
str: "[10,20,30]"
rascal>itoString(["zebra", "elephant", "snake", "owl"]);
str: "[\"zebra\",\"elephant\",\"snake\",\"owl\"]"
----

[[List-unzip]]
## unzip

.Function 
* `tuple[list[&T],list[&U]] unzip(list[tuple[&T,&U]] lst)`
          * `tuple[list[&T],list[&U],list[&V]] unzip(list[tuple[&T,&U,&V]] lst)`
          

.Synopsis
Make a pair (triple) of lists from a list of pairs (triples).

.Description
Also see <<List-unzip>>;

.Examples
[source,rascal-shell]
----
rascal>import List;
ok
rascal>unzip([<3,"thirty">, <1,"ten">, <4,"forty">]);
tuple[list[int],list[str]]: <[3,1,4],["thirty","ten","forty"]>
rascal>unzip([<3,"thirty",300>, <1,"ten",100>, <4,"forty",400>]);
tuple[list[int],list[str],list[int]]: <[3,1,4],["thirty","ten","forty"],[300,100,400]>
----

[[List-upTill]]
## upTill

.Function 
`list[int] upTill(int n)`

.Synopsis
Returns the list 0,1..n-1.
.Description
Returns the list `0`, `1`, .., `n-1`, this is slightly faster than `[0..n]`, since the returned values are shared.

.Examples
[source,rascal-shell]
----
rascal>import List;
ok
rascal>upTill(10);
list[int]: [0,1,2,3,4,5,6,7,8,9]
----

[[List-zip]]
## zip

.Function 
* `list[tuple[&T first, &U second]] zip(list[&T] a, list[&U] b)`
          * `list[tuple[&T first, &U second, &V third]] zip(list[&T] a, list[&U] b, list[&V] c)`
          

.Synopsis
Make a list of pairs from two (three) lists of the same length.

.Description
Also see <<List-unzip>>.

.Examples
[source,rascal-shell]
----
rascal>import List;
ok
rascal>zip([3, 1, 4], ["thirty", "ten", "forty"]);
lrel[int,str]: [
  <3,"thirty">,
  <1,"ten">,
  <4,"forty">
]
rascal>zip([3, 1, 4], ["thirty", "ten", "forty"], [300, 100, 400]);
lrel[int,str,int]: [
  <3,"thirty",300>,
  <1,"ten",100>,
  <4,"forty",400>
]
----

:leveloffset: +1

:leveloffset: -1