
[[Basic-Bubble]]
# Bubble
:concept: Basic/Bubble

.Synopsis
Variout styles to write bubble sort.

.Syntax

.Types

.Function

.Description
http://en.wikipedia.org/wiki/Bubble_sort[Bubble sort] is a classical (albeit not the most efficient) technique to sort lists of values.
We present here several styles to implement bubble sort. 
Also see link:{Libraries}#List-sort[sort] for a more efficient library function for sorting.

.Examples
[source,rascal]
----
include::{LibDir}demo/basic/Bubble.rsc[tags=module]
----
                
`sort1` is a classic, imperative style, implementation of bubble sort: it iterates over consecutive pairs of elements and
when a not-yet-sorted pair is encountered, the elements are exchanged, and `sort1` is applied recursively to the whole list.

`sort2` uses list matching and consists of a switch with two cases:

*  a case matching a list with two consecutive elements that are unsorted. Observe that when the pattern of a case matches,
   the case as a whole can still fail.
*  a default case.


`sort3` also uses list matching but in a more declarative style: as long as there are unsorted elements in the list (possibly with intervening elements), exchange them.

`sort4` is identical to `sort3`, except that the shorter `*`-notation for list variables is used and that the type declaration for the
the non-list variables has been omitted.

`sort5` uses tail recursion to reach a fixed point instead of a while loop. One alternative matches lists with out-of-order elements, while the default alternative returns the list if no out-of-order elements are found.

Let's put them to the test:
[source,rascal-shell]
----
rascal>import demo::basic::Bubble;
rascal2rvm: Parsing and checking |std:///demo/basic/Bubble.rsc|
rascal2rvm: Compiling |std:///demo/basic/Bubble.rsc|
r2mu: entering ... demo::basic::Bubble
mu2rvm: Compiling module demo::basic::Bubble
Compiling |std:///demo/basic/Bubble.rsc|: check: 20, compile: 825, total: 845 ms
compile: Writing RVMModule |compressed+home:///bin-console/demo/basic/Bubble.rvm.gz|
Removing |compressed+home:///bin-console/ConsoleInput_imports.rvm.gz|
ok
rascal>L = [9,8,7,6,5,4,3,2,1];
list[int]: [9,8,7,6,5,4,3,2,1]
rascal>sort1(L);
list[int]: [1,2,3,4,5,6,7,8,9]
rascal>sort2(L);
list[int]: [1,2,3,4,5,6,7,8,9]
rascal>sort3(L);
list[int]: [1,2,3,4,5,6,7,8,9]
rascal>sort4(L);
list[int]: [1,2,3,4,5,6,7,8,9]
rascal>sort5(L);
list[int]: [1,2,3,4,5,6,7,8,9]
----


.Benefits

.Pitfalls


:leveloffset: +1

:leveloffset: -1