
[[Prelude-Node]]


[[Prelude-Node]]
# Node
:concept: Prelude/Node
.Usage
`import Node;`


.Synopsis
Library functions for nodes.

.Description

For operators on nodes see link:{RascalLang}#Values-Node[Node] in the Rascal Language Reference.

The following functions are defined for nodes:


[[Node-arity]]
## arity

.Function 
`int arity(node T)`

.Synopsis
Determine the number of children of a node.

.Examples
[source,rascal-shell]
----
rascal>import Node;
ok
rascal>arity("f"(10, "abc"));
int: 2
rascal>arity("f"(10, "abc", false));
int: 3
----

[[Node-delAnnotation]]
## delAnnotation

.Function 
`&T <: node delAnnotation(&T <: node x, str label)`

.Synopsis
Delete a specific annotation from a node.

.Examples
[source,rascal-shell]
----
rascal>import Node;
ok
rascal>F = setAnnotations("f"(10, "abc"), ("color" : "red", "size" : "large"));
node: "f"(10,"abc")[
  @size="large",
  @color="red"
]
rascal>delAnnotation(F, "size");
node: "f"(10,"abc")[
  @color="red"
]
----

[[Node-delAnnotations]]
## delAnnotations

.Function 
`&T <: node  delAnnotations(&T <: node x)`

.Synopsis
Delete all annotations from a node.

.Examples
[source,rascal-shell]
----
rascal>import Node;
ok
rascal>F = setAnnotations("f"(10, "abc"), ("color" : "red", "size" : "large"));
node: "f"(10,"abc")[
  @size="large",
  @color="red"
]
rascal>delAnnotations(F);
node: "f"(10,"abc")
----

[[Node-delAnnotationsRec]]
## delAnnotationsRec

.Function 
`&T delAnnotationsRec(&T v)`

.Synopsis
Delete recursively all annotations from all nodes in a value.

.Examples
[source,rascal-shell]
----
rascal>import Node;
ok
rascal>G = setAnnotations("g"("def"), ("level" : "20", "direction" : "north"));
node: "g"("def")[
  @level="20",
  @direction="north"
]
rascal>F = setAnnotations("f"(10, G), ("color" : "red", "size" : "large"));
node: "f"(
  10,
  "g"("def")[
    @level="20",
    @direction="north"
  ])[
  @size="large",
  @color="red"
]
rascal>delAnnotationsRec(F);
node: "f"(
  10,
  "g"("def"))
----

[[Node-getAnnotations]]
## getAnnotations

.Function 
`map[str,value] getAnnotations(node x)`

.Synopsis
Retrieve the annotations of a node value as a map.

.Examples

[source,rascal-shell]
----
rascal>import Node;
ok
----
Declare two string-valued annotation on nodes, named color, respectively, size:
[source,rascal-shell]
----
rascal>anno str node@color;
ok
rascal>anno str node@size;
ok
----
Create a node with two annotations:
[source,rascal-shell]
----
rascal>F = setAnnotations("f"(10, "abc"), ("color" : "red", "size" : "large"));
node: "f"(10,"abc")[
  @size="large",
  @color="red"
]
----
and retrieve those annotations:
[source,rascal-shell]
----
rascal>getAnnotations(F);
map[str, str]: ("size":"large","color":"red")
rascal>F@color;
str: "red"
----

[[Node-getChildren]]
## getChildren

.Function 
`list[value] getChildren(node T)`

.Synopsis
Get the children of a node.

.Examples
[source,rascal-shell]
----
rascal>import Node;
ok
rascal>getChildren("f"(10, "abc"));
list[value]: [10,"abc"]
----

[[Node-getKeywordParameters]]
## getKeywordParameters

.Function 
`map[str,value] getKeywordParameters(node T)`

.Synopsis
Get the keyword parameters of a node.

.Examples
[source,rascal-shell]
----
rascal>import Node;
ok
rascal>getKeywordParameters("f"(10, "abc", height=0));
map[str, int]: ("height":0)
----

[[Node-setKeywordParameters]]
## setKeywordParameters

.Function 
`&T <: node setKeywordParameters(&T <: node x, map[str,value] keywordParameters)`

.Synopsis
Set the keyword parameters of a node.

.Examples
[source,rascal-shell]
----
rascal>import Node;
ok
rascal>setKeywordParameters("f"(10, "abc"), ("height":0));
node: "f"(10,"abc",height=0)
----

[[Node-getName]]
## getName

.Function 
`str getName(node T)`

.Synopsis
Determine the name of a node.

.Examples
[source,rascal-shell]
----
rascal>import Node;
ok
rascal>getName("f"(10, "abc"));
str: "f"
----

[[Node-makeNode]]
## makeNode

.Function 
`node makeNode(str N, value V..., map[str, value] keywordParameters = ())`

.Synopsis
Create a node given its function name and arguments.

.Examples
[source,rascal-shell]
----
rascal>import Node;
ok
rascal>makeNode("f", [10, "abc"]);
node: "f"(10,"abc")
----

[[Node-setAnnotations]]
## setAnnotations

.Function 
`&T <: node setAnnotations(&T <: node x, map[str, value] annotations)`

.Synopsis
Add a map of annotations to a node value.

.Description
Set the annotations on node value `x` as described by the map `annotations`.

.Examples
[source,rascal-shell]
----
rascal>import Node;
ok
rascal>setAnnotations("f"(10, "abc"), ("color" : "red", "size" : "large"));
node: "f"(10,"abc")[
  @size="large",
  @color="red"
]
----

.Benefits

.Pitfalls
This function may result in run-time type errors later if
you store a value with a label that has an incomparable annotation type
declared.

[[Node-unset]]
## unset

.Function 
* `&T <: node unset(&T <: node x, str label)`
          * `&T <: node unset(&T <: node x)`
          

.Synopsis
Set a specific parameter back to default on a node.

[[Node-unsetRec]]
## unsetRec

.Function 
`&T <: node unsetRec(&T <: node x)`



[[Node-toString]]
## toString

.Function 
`str toString(node T)`

.Synopsis
Convert a node to a string.

.Examples
[source,rascal-shell]
----
rascal>import Node;
ok
rascal>F = setAnnotations("f"(10, "abc"), ("color" : "red", "size" : "large"));
node: "f"(10,"abc")[
  @size="large",
  @color="red"
]
rascal>toString(F);
str: "\"f\"(10,\"abc\")[@size=\"large\",@color=\"red\"]"
----

[[Node-itoString]]
## itoString

.Function 
`str itoString(node T)`

.Synopsis
Convert a node to an indented string.

.Examples
[source,rascal-shell]
----
rascal>import Node;
ok
rascal>F = setAnnotations("f"(10, "abc"), ("color" : "red", "size" : "large"));
node: "f"(10,"abc")[
  @size="large",
  @color="red"
]
rascal>itoString(F);
str: "\"f\"(10,\"abc\")[\n  @size=\"large\",\n  @color=\"red\"\n]"
----

:leveloffset: +1

:leveloffset: -1