[[Basic-Squares]]
# Squares
:concept: Basic/Squares

.Synopsis
Print a list of squares

.Syntax

.Types

.Function

.Description

.Examples
How can we print a list of squares? Here is a solution:
[source,rascal]
----
include::{LibDir}demo/basic/Squares.rsc[tags=module]
----
           
<1> The link::{Rascal}#Prelude-IO[IO] module is imported since we want to print things using `println`.

<2> link::{Rascal}#Values-String[String] interpolation is used several times.
    Here the value of `N` is inserted in the header message.

<3> The values of `I` and `I * I` are inserted in each line that is printed.

<4> Define an alternative implementation `squareTemplate` that is based on string templates 
    and returns a string value instead of printing the results itself.

Here is how `square` can be used:
[source,rascal-shell]
----
rascal>import demo::basic::Squares;
ok
rascal>squares(9);
Table of squares from 1 to 9

1 squared = 1
2 squared = 4
3 squared = 9
4 squared = 16
5 squared = 25
6 squared = 36
7 squared = 49
8 squared = 64
9 squared = 81
list[void]: []
----

`squaresTemplate` gives a similar result but now as a string:
[source,rascal-shell]
----
rascal>squaresTemplate(9);
str: "Table of squares from 1 to 9\n\n  1 squared = 1\n  2 squared = 4\n  3 squared = 9\n  4 squared = 16\n  5 squared = 25\n  6 squared = 36\n  7 squared = 49\n  8 squared = 64\n  9 squared = 81"
----

To get a truly identical result we have to import the link::{Rascal}#Prelude-IO[IO] module 
and print the value of `squaresTemplate`:
[source,rascal-shell]
----
rascal>import IO;
ok
rascal>println(squaresTemplate(9));
Table of squares from 1 to 9

  1 squared = 1
  2 squared = 4
  3 squared = 9
  4 squared = 16
  5 squared = 25
  6 squared = 36
  7 squared = 49
  8 squared = 64
  9 squared = 81
ok
----


.Benefits

.Pitfalls


:leveloffset: +1

:leveloffset: -1