[[Values-Node]]
# Node
:concept: Expressions/Values/Node

.Synopsis
Node values.

.Syntax
`_Exp_~0~ ( _Exp_~1~, _Exp_~2~, ... )`

.Types

[cols="10,10,10,10,60"]
|====
|`_Exp~0~_`  | `_Exp~1~_` | `_Exp~2~_` | ... | `_Exp~0~_ ( _Exp~1~_, _Exp~2~_, ... )` 

| `str`      | `value`    | `value`    | ... | `node`                              
|====

.Usage

.Function

.Description
Values of type `node` represent untyped trees and are constructed as follows:

*  the string value of _Exp~0~_ is the node name;
*  zero or more expressions of type `value` are the node\'s children.


Nodes can have <<Declarations-Annotation>>s.

The following are provided for nodes:

**** <<Node-Equal,Node Equal>>: Equal operator on node values.
**** <<Node-GreaterThan,Node GreaterThan>>: Greater than operator on node values.
**** <<Node-GreaterThanOrEqual,Node GreaterThanOrEqual>>: Greater than or equal operator on node values.
**** <<Node-LessThan,Node LessThan>>: Less than operator on node values.
**** <<Node-LessThanOrEqual,Node LessThanOrEqual>>: Less than or equal operator on node values.
**** <<Node-NotEqual,Node NotEqual>>: Not equal operator on node values.
**** <<Node-Slice,Node Slice>>: Retrieve a slice of a node's argument list.
**** <<Node-Subscription,Node Subscription>>: Retrieve an argument of a node via its index.

.Examples

A node with name "my_node" and three arguments
[source,rascal-shell]
----
rascal>"my_node"(1, true, "abc");
node: "my_node"(1,true,"abc")
----
A nested node structure:
[source,rascal-shell]
----
rascal>"my_node1"(1, "my_node2"(3.5, ["a", "b", "c"]), true);
node: "my_node1"(
  1,
  "my_node2"(
    3.5,
    ["a","b","c"]),
  true)
----

.Benefits

.Pitfalls


:leveloffset: +1
include::Equal/Equal.adoc[Equal]

include::GreaterThan/GreaterThan.adoc[GreaterThan]

include::GreaterThanOrEqual/GreaterThanOrEqual.adoc[GreaterThanOrEqual]

include::LessThan/LessThan.adoc[LessThan]

include::LessThanOrEqual/LessThanOrEqual.adoc[LessThanOrEqual]

include::NotEqual/NotEqual.adoc[NotEqual]

include::Slice/Slice.adoc[Slice]

include::Subscription/Subscription.adoc[Subscription]


:leveloffset: -1