
[[Statements-While]]
# While
:concept: Statements/While



.Synopsis
While loop.



.Syntax
`while ( _Exp_ ) _Statement_;`

.Types

.Function

.Description
The Boolean expression _Exp_ is evaluated repeatedly and _Statement_ is executed when the test is true. 
Execution ends the first time that the test yields false. 
The test _Exp_ is executed from scratch in each repetition and only the first `true` value (if any) is used.
This is relevant when _Exp_ contains a <<Boolean Match>> or <<Boolean NoMatch>> operator.

By default, the value of a while statement is the empty list. In general, the value of a while statement 
consists of all values contributed by <<Statements-Append>> statements that are executed during the repeated execution 
of its body _Statement_.

.Examples
[source,rascal-shell]
----
rascal>import IO;
ok
rascal>int n = 3;
int: 3
rascal>while( n > 0 ) { println("n = <n>"); n -= 1; }
n = 3
n = 2
n = 1
list[void]: []
----
Now build a list result using the `append` statement:
[source,rascal-shell]
----
rascal>n = 3;
int: 3
rascal>while (n > 0) { append n * n; n -= 1; }
list[int]: [9,4,1]
----

Just to be sure, a <<List-Comprehension>> is the superior way to write this:
[source,rascal-shell]
----
rascal>[n * n | n <- [3 .. 1]];
list[int]: [9,4]
----

.Benefits

.Pitfalls


:leveloffset: +1

:leveloffset: -1