
[[Common-WordReplacement]]
# Word Replacement
:concept: Common/WordReplacement

.Synopsis
Replace words in a string.

.Syntax

.Types

.Function

.Description
Suppose you are a book editor and want to ensure that all chapter
and section titles are properly capitalized. Here is how to do this. 

.Examples
[source,rascal]
----
include::{LibDir}demo/common/WordReplacement.rsc[tags=module]
----

                
<1> We start by introducing a helper function `capitalize` that does the actual capitalization of a single word.
    See link:{RascalLang}#Patterns-Regular[Regular Pattern] for details about regular expression patterns.
    Next we give two versions of a capitalization functions for a sentence:

<2> `capAll1` uses a while loop to find subsequent words and to replace them by a capitalized version.
<3> `capAll2` uses a [Rascal:Visit] to visit all words in the sentence and replace them by a capitalized version.


Here are some examples:

[source,rascal-shell]
----
rascal>import demo::common::WordReplacement;
rascal2rvm: Parsing and checking |std:///demo/common/WordReplacement.rsc|
rascal2rvm: Compiling |std:///demo/common/WordReplacement.rsc|
r2mu: entering ... demo::common::WordReplacement
mu2rvm: Compiling module demo::common::WordReplacement
Compiling |std:///demo/common/WordReplacement.rsc|: check: 13, compile: 905, total: 918 ms
compile: Writing RVMModule |compressed+home:///bin-console/demo/common/WordReplacement.rvm.gz|
Removing |compressed+home:///bin-console/ConsoleInput_imports.rvm.gz|
ok
rascal>capitalize("rascal");
str: "Rascal"
rascal>capAll1("turn this into a capitalized title")
str: "Turn This Into A Capitalized Title"
rascal>capAll2("turn this into a capitalized title")
str: "Turn This Into A Capitalized Title"
----

.Benefits

.Pitfalls


:leveloffset: +1

:leveloffset: -1