
[[Prelude-Set]]


[[Prelude-Set]]
# Set
:concept: Prelude/Set
.Usage
`import Set;`


.Synopsis
Library functions for sets.

.Usage

.Description

For operators on sets see link:{RascalLang}#Values-Set[Set] in the Rascal Language Reference.

The following functions are defined for sets:


[[Set-classify]]
## classify

.Function 
`map[&K,set[&V]] classify(set[&V] input, &K (&V) getClass)`

.Synopsis
Classify elements in a set.

.Examples
We classify animals by their number of legs.
[source,rascal-shell]
----
rascal>import Set;
ok
----
Create a map from animals to number of legs.
[source,rascal-shell]
----
rascal>legs = ("bird": 2, "dog": 4, "human": 2, "snake": 0, "spider": 8, "millepede": 1000, "crab": 8, "cat": 4);
map[str, int]: ("snake":0,"spider":8,"human":2,"crab":8,"cat":4,"bird":2,"dog":4,"millepede":1000)
----
Define function `nLegs` that returns the number of legs for each animal (or `0` when the animal is unknown):
[source,rascal-shell]
----
rascal>int nLegs(str animal){
>>>>>>>    return legs[animal] ? 0;
>>>>>>>}
ok
----
Now classify a set of animals:
[source,rascal-shell]
----
rascal>classify({"bird", "dog", "human", "spider", "millepede", "zebra", "crab", "cat"}, nLegs);
map[int, set[str]]: (
  8:{"spider","crab"},
  2:{"human","bird"},
  4:{"cat","dog"},
  1000:{"millepede"},
  0:{"zebra"}
)
----

[[Set-getOneFrom]]
## getOneFrom

.Function 
`&T getOneFrom(set[&T] st) throws EmptySet`

.Synopsis
Pick a random element from a set.

.Description

.Examples
[source,rascal-shell]
----
rascal>import Set;
ok
rascal>getOneFrom({1,2,3,4});
int: 4
rascal>getOneFrom({1,2,3,4});
int: 1
rascal>getOneFrom({1,2,3,4});
int: 4
rascal>getOneFrom({1,2,3,4});
int: 4
----

[[Set-getFirstFrom]]
## getFirstFrom

.Function 
`&T getFirstFrom(set[&T] st) throws EmptySet`

.Synopsis
Get "first" element from a set.

.Description
Get "first" element of a set. Of course, sets are unordered and do not have a first element.
However, we may assume that sets are internally ordered in some way and this ordering is reproducible.
Applying `getFirstFrom` on the same set will always returns the same element.

.Benefits
This function helps to make set-based code more deterministic, for instance, for testing purposes.

[[Set-group]]
## group

.Function 
`set[set[&T]] group(set[&T] input, bool (&T a, &T b) similar)`

.Synopsis
Group elements in a set given an equivalence function.

.Examples
We classify animals by their number of legs.
[source,rascal-shell]
----
rascal>import Set;
ok
----
Create a map from animals to number of legs.
[source,rascal-shell]
----
rascal>legs = ("bird": 2, "dog": 4, "human": 2, "snake": 0, "spider": 8, "millepede": 1000, "crab": 8, "cat": 4);
map[str, int]: ("snake":0,"spider":8,"human":2,"crab":8,"cat":4,"bird":2,"dog":4,"millepede":1000)
----
Define function `nLegs` that returns the number of legs fro each animal (or `0` when the animal is unknown):
[source,rascal-shell]
----
rascal>int nLegs(str animal){
>>>>>>>    return legs[animal] ? 0;
>>>>>>>}
ok
rascal>bool similar(str a, str b) = nLegs(a) == nLegs(b);
ok
----
Now group a set of animals:
[source,rascal-shell]
----
rascal>group({"bird", "dog", "human", "spider", "millepede", "zebra", "crab", "cat"}, similar);
Call stack (most recent first):
	group({"spider","zebra","human","crab","cat","bird","dog","millepede"}, OverloadedFunctionInstance[functions: ConsoleInput/similar(str();str();)#7/13], {}) at |std:///Set.rsc|(3418,65,<128,10>,<128,75>)
	main([]) at |test-modules:///ConsoleInput.rsc|(175,87,<11,15>,<11,102>)
ok
----
WARNING: check compiler.

[[Set-index]]
## index

.Function 
`map[&T,int] index(set[&T] s)`

.Synopsis
Map set elements to a fixed index.

.Examples
[source,rascal-shell]
----
rascal>import Set;
ok
rascal>index({"elephant", "zebra", "snake"});
map[str, int]: ("snake":2,"zebra":1,"elephant":0)
----

[[Set-isEmpty]]
## isEmpty

.Function 
`bool isEmpty(set[&T] st)`

.Synopsis
Test whether a set is empty.

.Description
Yields `true` if `s` is empty, and `false` otherwise.

.Examples
[source,rascal-shell]
----
rascal>import Set;
ok
rascal>isEmpty({1, 2, 3});
bool: false
rascal>isEmpty({});
bool: true
----

[[Set-mapper]]
## mapper

.Function 
`set[&U] mapper(set[&T] st, &U (&T) fn)`

.Synopsis
Apply a function to all set elements and return set of results.

.Description
Return a set obtained by applying function `fn` to all elements of set `s`.

.Examples
[source,rascal-shell]
----
rascal>import Set;
ok
rascal>int incr(int x) { return x + 1; }
ok
rascal>mapper({1, 2, 3, 4}, incr);
set[int]: {5,3,2,4}
----

[[Set-max]]
## max

.Function 
`&T max(set[&T] st)`

.Synopsis
Determine the largest element of a set.

.Examples
[source,rascal-shell]
----
rascal>import Set;
ok
rascal>max({1, 3, 5, 2, 4});
int: 5
rascal>max({"elephant", "zebra", "snake"});
str: "zebra"
----

[[Set-min]]
## min

.Function 
`&T min(set[&T] st)`

.Synopsis
Determine the smallest element of a set.

.Examples
[source,rascal-shell]
----
rascal>import Set;
ok
rascal>min({1, 3, 5, 4, 2});
int: 1
----

[[Set-power]]
## power

.Function 
`set[set[&T]] power(set[&T] st)`

.Synopsis
Determine the powerset of a set.

.Description
Returns a set with all subsets of `s`.

.Examples
[source,rascal-shell]
----
rascal>import Set;
ok
rascal>power({1,2,3,4});
set[set[int]]: {
  {},
  {1,2,4},
  {1},
  {3,2,4},
  {3},
  {1,3,2,4},
  {1,3},
  {2},
  {4},
  {1,2},
  {1,4},
  {3,2},
  {3,4},
  {1,3,2},
  {1,3,4},
  {2,4}
}
----

[[Set-power1]]
## power1

.Function 
`set[set[&T]] power1(set[&T] st)`

.Synopsis
The powerset (excluding the empty set) of a set value.

.Description
Returns all subsets (excluding the empty set) of `s`.

.Examples
[source,rascal-shell]
----
rascal>import Set;
ok
rascal>power1({1,2,3,4});
set[set[int]]: {
  {1,2,4},
  {1},
  {3,2,4},
  {3},
  {1,3,2,4},
  {1,3},
  {2},
  {4},
  {1,2},
  {1,4},
  {3,2},
  {3,4},
  {1,3,2},
  {1,3,4},
  {2,4}
}
----

[[Set-reducer]]
## reducer

.Function 
`&T reducer(set[&T] st, &T (&T,&T) fn, &T unit)`

.Synopsis
Apply a function to successive elements of a set and combine the results (__deprecated__).

.Description
Apply the function `fn` to successive elements of set `s` starting with `unit`.

.Examples
[source,rascal-shell]
----
rascal>import Set;
ok
rascal>int add(int x, int y) { return x + y; }
ok
rascal>reducer({10, 20, 30, 40}, add, 0); 
int: 100
----

.Pitfalls
WARNING: This function is *deprecated*, use a link:{rascalLang}#Expressions-Reducer[reducer] instead.

[[Set-size]]
## size

.Function 
`int size(set[&T] st)`

.Synopsis
Determine the number of elements in a set.

.Examples
[source,rascal-shell]
----
rascal>import Set;
ok
rascal>size({1,2,3,4});
int: 4
rascal>size({"elephant", "zebra", "snake"});
int: 3
rascal>size({});
int: 0
----

[[Set-sum]]
## sum

.Function 
* `(&T <:num) sum(set[(&T <:num)] _:{})`
          * `default (&T <:num) sum({(&T <: num) e, *(&T <: num) r})`
          



[[Set-getOneFrom]]
## getOneFrom

.Function 
`&T getOneFrom(set[&T] st) throws EmptySet`

.Synopsis
Pick an arbitrary element from a set.

.Description

.Examples

[source,rascal-shell]
----
rascal>import Set;
ok
rascal>getOneFrom({"elephant", "zebra", "snake"});
str: "elephant"
rascal>getOneFrom({"elephant", "zebra", "snake"});
str: "zebra"
rascal>getOneFrom({"elephant", "zebra", "snake"});
str: "zebra"
rascal>getOneFrom({"elephant", "zebra", "snake"});
str: "zebra"
----

[[Set-takeOneFrom]]
## takeOneFrom

.Function 
`tuple[&T, set[&T]] takeOneFrom(set[&T] st) throws EmptySet`

.Synopsis
Remove an arbitrary element from a set, returns the element and a set without that element.

.Description
Remove an arbitrary element from set `s` and return a tuple consisting of the element and a set without that element.
 Also see <<Set-getOneFrom>>.

.Examples
[source,rascal-shell]
----
rascal>import Set;
ok
rascal>takeOneFrom({1, 2, 3, 4});
tuple[int,set[int]]: <4,{1,3,2}>
rascal>takeOneFrom({1, 2, 3, 4});
tuple[int,set[int]]: <3,{1,2,4}>
rascal>takeOneFrom({1, 2, 3, 4});
tuple[int,set[int]]: <2,{1,3,4}>
----

[[Set-takeFirstFrom]]
## takeFirstFrom

.Function 
`tuple[&T, set[&T]] takeFirstFrom(set[&T] st) throws EmptySet`

.Synopsis
Remove "first" element from a set, returns the element and a set without that element.

.Description
element of a set.

[[Set-toList]]
## toList

.Function 
`list[&T] toList(set[&T] st)`

.Synopsis
Convert a set to a list.

.Examples
[source,rascal-shell]
----
rascal>import Set;
ok
rascal>toList({1, 2, 3, 4});
list[int]: [4,2,3,1]
rascal>toList({"elephant", "zebra", "snake"});
list[str]: ["elephant","zebra","snake"]
----
Note that the same result can be obtained using splicing:
[source,rascal-shell]
----
rascal>s = {1,2,3,4};
set[int]: {1,3,2,4}
rascal>l = [*s];
list[int]: [1,3,2,4]
----

.Pitfalls
Recall that the elements of a set are unordered and that there is no guarantee in which order the set elements will be placed in the resulting list.

[[Set-toMap]]
## toMap

.Function 
`map[&A,set[&B]] toMap(rel[&A, &B] st)`

.Synopsis
Convert a set of tuples to a map; each key is associated with a set of values.

.Description
Convert a set of tuples to a map in which the first element of each tuple 
is associated with the set of second elements of all tuples with the same first element.

.Examples
[source,rascal-shell]
----
rascal>import Set;
ok
rascal>toMap({<"a", 1>, <"b", 2>, <"a", 10>});
map[str, set[int]]: (
  "a":{10,1},
  "b":{2}
)
----

[[Set-toMapUnique]]
## toMapUnique

.Function 
`map[&A,&B] toMapUnique(rel[&A, &B] st) throws MultipleKey`

.Synopsis
Convert a set of tuples to a map (provided that there are no multiple keys).

.Description
Convert a set of tuples to a map. The result should be a legal map (i.e., without multiple keys).

.Examples
[source,rascal-shell-error]
----
rascal>import Set;
ok
rascal>toMapUnique({<"a", 1>, <"b", 2>, <"c", 10>});
map[str, int]: ("a":1,"b":2,"c":10)
----
Now explore an erroneous example:
[source,rascal-shell-error]
----
rascal>toMapUnique({<"a", 1>, <"b", 2>, <"a", 10>});
MultipleKey("a")
Call stack (most recent first):
	toMapUnique({<"b",2>,<"a",1>,<"a",10>}, {}) at |std:///Set.rsc|(9683,552,<439,0>,<458,70>)
	main([]) at |test-modules:///ConsoleInput.rsc|(48,44,<4,15>,<4,59>)

ok
----

[[Set-toString]]
## toString

.Function 
`str toString(set[&T] st)`

.Synopsis
Convert a set to a string.

.Examples
[source,rascal-shell]
----
rascal>import Set;
ok
rascal>toString({1, 2, 3});
str: "{1,3,2}"
rascal>toString({"elephant", "zebra", "snake"});
str: "{\"snake\",\"zebra\",\"elephant\"}"
----

.Pitfalls
Recall that the elements of a set are unordered and that there is no guarantee in which order the set elements will be placed in the resulting string.

[[Set-itoString]]
## itoString

.Function 
`str itoString(set[&T] st)`

.Synopsis
Convert a set to an indented string.

.Examples
[source,rascal-shell]
----
rascal>import Set;
ok
rascal>toString({1, 2, 3});
str: "{1,3,2}"
rascal>toString({"elephant", "zebra", "snake"});
str: "{\"snake\",\"zebra\",\"elephant\"}"
----

.Pitfalls
Recall that the elements of a set are unordered and that there is no guarantee in which order the set elements will be placed in the resulting string.

[[Set-sort]]
## sort

.Function 
* `list[&T] sort(set[&T] s)`
          * `list[&T] sort(set[&T] l, bool (&T a, &T b) less)`
          

.Synopsis
Sort the elements of a set.

Sort the elements of a set:

*  Use the built-in ordering on values to compare list elements.
*  Give an additional `lessThan` function that will be used to compare elements. 

This function `lessThan` (<) function should implement a strict partial order, meaning:

*  that it is not reflexive, i.e. never `a < a`
*  is anti-symmetric, i.e. never `a < b && b < a`.
*  is transitive, i.e. if `a < b` and `b < c` then `a < c`.

.Examples
[source,rascal-shell]
----
rascal>import Set;
ok
rascal>import String;
ok
rascal>sort({10, 4, -2, 11, 100, 5});
list[int]: [-2,4,5,10,11,100]
rascal>fruits = {"mango", "strawberry", "pear", "pineapple", "banana", "grape", "kiwi"};
set[str]: {"mango","banana","pear","pineapple","grape","strawberry","kiwi"}
rascal>sort(fruits);
list[str]: ["banana","grape","kiwi","mango","pear","pineapple","strawberry"]
rascal>sort(fruits, bool(str a, str b){ return size(a) > size(b); });
list[str]: ["strawberry","pineapple","banana","mango","grape","kiwi","pear"]
----

[[Set-union]]
## union

.Function 
`set[&T] union(set[set[&T]] sets)`

.Synopsis
Flatten a set of sets into a single set.

:leveloffset: +1

:leveloffset: -1