
[[graphs-Graph]]


[[graphs-Graph]]
# Graph
:concept: analysis/graphs/Graph
.Usage
`import analysis::graphs::Graph;`



.Synopsis
A `Graph` datatype with associated functions.

.Types
`alias Graph[&T] = rel[&T from, &T to];`

.Description
The Graph data type is a binary relation and all operators and functions defined
on link:{rascalLang}#Values-Relation[relations] are also defined on Graphs.

The `Graph` library provides the following functions:



* <<Graph-Graph,Graph>>: 
* <<Graph-bottom,bottom>>: Determine the bottom nodes (leaves) of a graph.
      
* <<Graph-connectedComponents,connectedComponents>>: Determine the connected components of a graph.
      
* <<Graph-order,order>>: Compute topological order of the nodes in a graph.
      
* <<Graph-predecessors,predecessors>>: Determine the direct predecessors of a graph node.
      
* <<Graph-reach,reach>>: Determine the graph nodes reachable from a set of nodes.
      
* <<Graph-reachR,reachR>>: Determine the graph nodes reachable from a set of nodes using a restricted set of intermediate nodes.
      
* <<Graph-reachX,reachX>>: Determine the graph nodes reachable from a set of nodes excluding certain intermediate nodes.
      
* <<Graph-shortestPathPair,shortestPathPair>>: Determine the shortest path between two graph nodes.
      
* <<Graph-successors,successors>>: Determine the direct successors of a graph node.
      
* <<Graph-top,top>>: Determine the set of top nodes (roots) of a graph.
      

[[Graph-Graph]]
## Graph
.Types
[source,rascal]
----
alias Graph[&T] = rel[&T from, &T to];
----

[[Graph-bottom]]
## bottom

.Function 
`set[&T] bottom(Graph[&T] G)`


.Synopsis
Determine the bottom nodes (leaves) of a graph.

.Description
Returns the bottom nodes of Graph `G`, i.e., the leaf nodes that don't have any descendants.

.Examples
[source,rascal-shell]
----
rascal>import analysis::graphs::Graph;
rascal2rvm: Parsing and checking |std:///analysis/graphs/Graph.rsc|
rascal2rvm: Compiling |std:///analysis/graphs/Graph.rsc|
r2mu: entering ... analysis::graphs::Graph
rlib1 = Prelude, rlib2 = |std:///PreludeCompiled.class|
resolveLibOverriding org.rascalmpl.library.Prelude => org.rascalmpl.library.PreludeCompiled
mu2rvm: Compiling module analysis::graphs::Graph
Compiling |std:///analysis/graphs/Graph.rsc|: check: 25, compile: 619, total: 644 ms
compile: Writing RVMModule |compressed+home:///bin-console/analysis/graphs/Graph.rvm.gz|
Removing |compressed+home:///bin-console/ConsoleInput_imports.rvm.gz|
ok
rascal>bottom({<1,2>, <1,3>, <2,4>, <3,4>});
set[int]: {4}
----



[[Graph-connectedComponents]]
## connectedComponents

.Function 
`set[set[&T]] connectedComponents(Graph[&T] G)`


.Synopsis
Determine the connected components of a graph.

.Description
Returns the http://en.wikipedia.org/wiki/Connected_component_(graph_theory)[connected components] of Graph `G`, as sets of nodes. All nodes within one component are all reachable from one another, there are no paths between two nodes from different components. The graph is assumed to be undirected.

.Examples
[source,rascal-shell]
----
rascal>import analysis::graphs::Graph;
ok
rascal>connectedComponents({<1,2>, <1,3>, <4,5>, <5,6>});
set[set[int]]: {
  {5,4,6},
  {1,3,2}
}
----



[[Graph-order]]
## order

.Function 
`list[&T] order(Graph[&T] g)`


.Synopsis
Compute topological order of the nodes in a graph.

.Examples
[source,rascal-shell]
----
rascal>import  analysis::graphs::Graph;
ok
rascal>order({<3,4>, <1,2>, <2,4>, <1,3>});
list[int]: [1,3,2,4]
----



[[Graph-predecessors]]
## predecessors

.Function 
`set[&T] predecessors(Graph[&T] G, &T From)`


.Synopsis
Determine the direct predecessors of a graph node.

.Description
Returns the direct predecessors of node `From` in Graph `G`.

.Examples
[source,rascal-shell]
----
rascal>import analysis::graphs::Graph;
ok
rascal>predecessors({<1,2>, <1,3>, <2,4>, <3,4>}, 4);
set[int]: {3,2}
----



[[Graph-reach]]
## reach

.Function 
`set[&T] reach(Graph[&T] G, set[&T] Start)`


.Synopsis
Determine the graph nodes reachable from a set of nodes.

.Description
Returns the set of nodes in Graph `G` that are reachable from any of the nodes
in the set `Start`.



[[Graph-reachR]]
## reachR

.Function 
`set[&T] reachR(Graph[&T] G, set[&T] Start, set[&T] Restr)`


.Synopsis
Determine the graph nodes reachable from a set of nodes using a restricted set of intermediate nodes.

.Description
Returns the set of nodes in Graph `G` that are reachable from any of the nodes
in set `Start` using path that only use nodes in the set `Restr`.

.Examples
[source,rascal-shell]
----
rascal>import analysis::graphs::Graph;
ok
rascal>reachR({<1,2>, <1,3>, <2,4>, <3,4>}, {1}, {1, 2, 3});
set[int]: {3,2}
----



[[Graph-reachX]]
## reachX

.Function 
`set[&T] reachX(Graph[&T] G, set[&T] Start, set[&T] Excl)`


.Synopsis
Determine the graph nodes reachable from a set of nodes excluding certain intermediate nodes.

.Description
Returns set of nodes in Graph `G` that are reachable from any of the nodes
in `Start` via path that exclude nodes in `Excl`.

.Examples
[source,rascal-shell]
----
rascal>import analysis::graphs::Graph;
ok
rascal>reachX({<1,2>, <1,3>, <2,4>, <3,4>}, {1}, {2});
set[int]: {3,4}
----



[[Graph-shortestPathPair]]
## shortestPathPair

.Function 
`list[&T] shortestPathPair(Graph[&T] G, &T From, &T To)`


.Synopsis
Determine the shortest path between two graph nodes.

.Description
Returns the shortest path between nodes `From` and `To` in Graph `G`.



[[Graph-successors]]
## successors

.Function 
`set[&T] successors(Graph[&T] G, &T From)`


.Synopsis
Determine the direct successors of a graph node.

.Description
Returns the direct successors of node `From` in Graph `G`.

.Examples
[source,rascal-shell]
----
rascal>import analysis::graphs::Graph;
ok
rascal>successors({<1,2>, <1,3>, <2,4>, <3,4>}, 1);
set[int]: {3,2}
----



[[Graph-top]]
## top

.Function 
`set[&T] top(Graph[&T] G)`


.Synopsis
Determine the set of top nodes (roots) of a graph.

.Description
Returns the top nodes of Graph `G`, i.e., the root nodes that do not have any predecessors.

.Examples
[source,rascal-shell]
----
rascal>import analysis::graphs::Graph;
ok
rascal>top({<1,2>, <1,3>, <2,4>, <3,4>});
set[int]: {1}
----



:leveloffset: +1

:leveloffset: -1