
[[Declarations-Alias]]
# Alias Declaration
:concept: Declarations/Alias

.Synopsis
Declare an alias for a type.

.Index
alias

.Syntax
`alias _Name_  = _Type_;`

.Types

.Function

.Description
Everything can be expressed using the elementary types and values that are provided by Rascal. 
However, for the purpose of documentation and readability it is sometimes better to use a descriptive name as type indication, rather than an elementary type.  The use of aliases is a good way to document your intentions. 

An alias declaration states that _Name_ can be used everywhere instead of the already defined type _Type_. 
Both types are thus structurally equivalent. 

.Examples
[source,rascal-shell]
----
----
Introduce two aliases `ModuleId` and `Frequency` for the type str.
[source,rascal-shell]
----
rascal>alias ModuleId = str;
ok
rascal>alias Frequency = int;
ok
----
Another example is an alias definition for a graph containing integer nodes:
[source,rascal-shell]
----
rascal>alias IntGraph = rel[int,int];
ok
----
Note that the Rascal Standard Library provides a graph data type that is defined as follows:
[source,rascal-shell]
----
rascal>alias Graph[&T] = rel[&T, &T];
ok
----
In other words the standard graph datatype can be parameterized with any element type.

See <<Type Parameters>> for other examples parameterized alias declarations.

.Benefits

.Pitfalls


:leveloffset: +1

:leveloffset: -1