
[[Common-Derivative]]
# Derivative
:concept: Common/Derivative

.Synopsis
Symbolic differentiation.

.Syntax

.Types

.Function

.Description
Computing the http://en.wikipedia.org/wiki/Differentiation_(mathematics)[derivative] of an expression with respect to some variable is a classical calculus problem. Loosely speaking, a derivative can be thought of as how much one quantity is changing in response to changes in some other quantity; for example, the derivative of the position of a moving object with respect to time is the object's instantaneous velocity.

We present here rules for determining the derivative `dE/dX` of simple expressions `E` for a given variable `X`. Recall that for number `N`, variables `X` and `Y`, and expressions `E1` and `E2` the following rules apply:

*  `dN / dX = 0`.
*  `dX / dX = 1`.
*  `dX / dY = 0`, when `X != Y`.
*  `d(E1 + E2) /dX = dE1 / dX + d E2 /dX`.
*  `d(E1 * E2) / dX =  (d E1 / dX  * E2) + (E1 * d E2 /dX)`.


.Examples

Here is our solution followed by a list of explanations:

[source,rascal]
----
include::{LibDir}demo/common/Derivative.rsc[tags=module]
----

<1> Define a data type `Exp` to represent expressions.
<2> Introduce an example expression `E` for later use.
<3> Define the actual differentiation function `dd`. Observe that this definition depends on the use of patterns in function declarations, see [Rascal:Function].
<4> Define simplification rules. 
<5> A default rule is give for the case that no simplification applies.
<6> Define the actual simplication function `simplify` that performs a bottom up traversal of the expression, application simplification
rules on the the up.

                
Let's differentiate the example expression `E`:
[source,rascal-shell]
----
rascal>import demo::common::Derivative;
rascal2rvm: Parsing and checking |std:///demo/common/Derivative.rsc|
rascal2rvm: Compiling |std:///demo/common/Derivative.rsc|
r2mu: entering ... demo::common::Derivative
mu2rvm: Compiling module demo::common::Derivative
Compiling |std:///demo/common/Derivative.rsc|: check: 15, compile: 607, total: 622 ms
compile: Writing RVMModule |compressed+home:///bin-console/demo/common/Derivative.rvm.gz|
Removing |compressed+home:///bin-console/ConsoleInput_imports.rvm.gz|
ok
rascal>dd(E, var("x"));
Exp: add(
  add(
    mul(
      con(0),
      var("y")),
    mul(
      con(3),
      con(0))),
  add(
    mul(
      con(0),
      var("x")),
    mul(
      con(5),
      con(1))))
----
As you can see, we managed to compute a derivative, but the result is far more complex than we would like.
This is where simplification comes in. First try a simple case:
[source,rascal-shell]
----
rascal>simplify(mul(var("x"), add(con(3), con(5))));
Exp: mul(
  var("x"),
  con(8))
----
Now apply simplification to the result of differentiation:
[source,rascal-shell]
----
rascal>simplify(dd(E, var("x")));
Exp: con(5)
----

.Benefits

.Pitfalls


:leveloffset: +1

:leveloffset: -1