
[[Dynamic-NoSuchKey]]
# NoSuchKey
:concept: Dynamic/NoSuchKey

.Synopsis
A map does not contain a requested key.

.Syntax

.Types

.Function
.Usage

.Description
Rascal provides many operations and functions on maps, 
see link:{RascalLang}#Values-Map[map values] and link:{Libraries}#Prelude-Map[map functions].
This error is generated when a function or operation cannot find a requested key value in a map.

Remedies: 

*  Use the 
   link:{RascalLang}#Boolean-isDefined[isDefined] and 
   link:{RascalLang}#Boolean-ifDefinedElse[ifDefinedElse] operator to guard a lookup in a map.
*  Catch the `NoSuchKey` yourself, see link:{RascalLang}#Statements-TryCatch[try catch].

.Examples
[source,rascal-shell-error]
----
----
Import the `Map` and `IO` libraries and introduce map `M`:
[source,rascal-shell-error]
----
rascal>import Map;
rascal2rvm: Parsing and checking |std:///Map.rsc|
rascal2rvm: Compiling |std:///Map.rsc|
r2mu: entering ... Map
rlib1 = Prelude, rlib2 = |std:///PreludeCompiled.class|
resolveLibOverriding org.rascalmpl.library.Prelude => org.rascalmpl.library.PreludeCompiled
mu2rvm: Compiling module Map
Compiling |std:///Map.rsc|: check: 68, compile: 293, total: 361 ms
compile: Writing RVMModule |compressed+home:///bin-console/Map.rvm.gz|
Removing |compressed+home:///bin-console/ConsoleInput_imports.rvm.gz|
ok
rascal>import IO;
ok
rascal>M = ("a" : 1, "b" : 2);
map[str, int]: ("a":1,"b":2)
----
Indexing `M` with a non-existing key gives an error:
[source,rascal-shell-error]
----
rascal>M["c"]
NoSuchKey("c") at |test-modules:///ConsoleInput.rsc|(76,6,<6,15>,<6,21>)
Call stack (most recent first):
	main([]) at |test-modules:///ConsoleInput.rsc|(76,6,<6,15>,<6,21>)

ok
----
Use the postfix isDefined operator `?` to test whether the value is defined:
[source,rascal-shell-error]
----
rascal>if(M["c"]?) println("defined"); else println("not defined");
not defined
ok
----
Or use the binary ifDefinedElse operator `?` to return an alternative value
when the value of `M["c"]` is undefined:
[source,rascal-shell-error]
----
rascal>M["c"] ? 3
int: 3
----
Yet another solution is to use try/catch.
First we import the Rascal exceptions (which are also included in `Prelude`):
[source,rascal-shell-error]
----
rascal>import Exception;
ok
rascal>try println(M["c"]); catch NoSuchKey(k): println("Key <k> does not exist");
Key c does not exist
ok
----

.Benefits

.Pitfalls


:leveloffset: +1

:leveloffset: -1