
[[Dynamic-NoSuchAnnotation]]
# NoSuchAnnotation
:concept: Dynamic/NoSuchAnnotation

.Synopsis
Annotation without a value.

.Syntax

.Types

.Function
       
.Usage

.Description
An link:{RascalLang}#Declarations-Annotation[annotation] can be associated with any node value
(including any link:{RascalLang}#Declarations-AlgebraicDataType[algebraic data type]).
This error is generated when the value of an annotation is requested but has not been defined.

Remedies:

*  Ensure that the annotation value is properly initialized for all relevant parts of the node value. 
*  Use the 
   link:{RascalLang}#Boolean-isDefined[isDefined] and 
   link:{RascalLang}#Boolean-ifDefinedElse[ifDefinedElse] operators to check whether the annotation value 
   is set and act accordingly.
*  Catch the `NoSuchAnnotation yourself`, see link:{RascalLang}#Statements-TryCatch[try catch].

.Examples
[source,rascal-shell-error]
----
rascal>data Fruit = apple(int n) | orange(int n);
ok
rascal>anno str Fruit @ quality;
ok
rascal>piece = orange(13);
Fruit: orange(13)
rascal>piece @ quality;
----
Use the unary postfix operator isDefined `?` to check whether the `quality` annotation is set:
[source,rascal-shell-error]
----
rascal>piece @ quality?;
----
Use the ternary operator ifDefinedElse `?` to compute an alternative value when the `quality` annotation is not set:
[source,rascal-shell-error]
----
rascal>piece @ quality ? "no quality value";
----
We can also catch the `NoSuchAnnotation` error. First import the Rascal exceptions (which are also included in `Prelude`)
and `IO`:
[source,rascal-shell-error]
----
rascal>import Exception;
ok
rascal>import IO;
ok
rascal>try piece @ quality; catch NoSuchAnnotation(l): println("No such annotation: <l>");
----
Finally, we can just assign a value to the `quality` annotation:
[source,rascal-shell-error]
----
rascal>piece @ quality = "excellent";
str: "excellent"
rascal>piece @ quality;
----

.Benefits

.Pitfalls


:leveloffset: +1

:leveloffset: -1