
[[Dynamic-EmptySet]]
# EmptySet
:concept: Dynamic/EmptySet

.Synopsis
Illegal operation on an empty set.

.Syntax

.Types

.Function
       
.Usage

.Description
Rascal provides many operations and functions on sets, see link:{rascalLang}#Values-Set[set values]
and link:{Libraries}#Prelude-Set[set functions].
This error is generated when a function or operations cannot handle the empty set.

Remedies:

*  Guard the function or operation with a test on the empty set (link:{Libraries}#Set-isEmpty[isEmpty]) and 
  take alternative action in that case.
*  Catch the `EmptySet` yourself, see link:{RascalLang}#Statements-TryCatch[try catch].

.Examples

Import the `Set` library and introduce `S` with an empty set as value:
[source,rascal-shell-error]
----
rascal>import Set;
rlib1 = Prelude, rlib2 = |std:///PreludeCompiled.class|
resolveLibOverriding org.rascalmpl.library.Prelude => org.rascalmpl.library.PreludeCompiled
rascal2rvm: Parsing and checking |std:///Set.rsc|
rascal2rvm: Compiling |std:///Set.rsc|
r2mu: entering ... Set
rlib1 = Prelude, rlib2 = |std:///PreludeCompiled.class|
resolveLibOverriding org.rascalmpl.library.Prelude => org.rascalmpl.library.PreludeCompiled
mu2rvm: Compiling module Set
Compiling |std:///Set.rsc|: check: 44, compile: 923, total: 967 ms
compile: Writing RVMModule |compressed+home:///bin-console/Set.rvm.gz|
rascal2rvm: Parsing and checking |std:///util/Math.rsc|
rascal2rvm: Compiling |std:///util/Math.rsc|
r2mu: entering ... util::Math
rlib1 = util.Math, rlib2 = |std:///util/MathCompiled.class|
resolveLibOverriding org.rascalmpl.library.util.Math => org.rascalmpl.library.util.Math
mu2rvm: Compiling module util::Math
Compiling |std:///util/Math.rsc|: check: 51, compile: 1325, total: 1376 ms
compile: Writing RVMModule |compressed+home:///bin-console/util/Math.rvm.gz|
Removing |compressed+home:///bin-console/ConsoleInput_imports.rvm.gz|
ok
rascal>S = {};
rlib1 = Prelude, rlib2 = |std:///PreludeCompiled.class|
resolveLibOverriding org.rascalmpl.library.Prelude => org.rascalmpl.library.PreludeCompiled
set[void]: {}
----
Taking an element from an empty set gives an error:
[source,rascal-shell-error]
----
rascal>getOneFrom(S);
rlib1 = Prelude, rlib2 = |std:///PreludeCompiled.class|
resolveLibOverriding org.rascalmpl.library.Prelude => org.rascalmpl.library.PreludeCompiled
EmptySet()
Call stack (most recent first):
	getOneFrom({}, {}) at |std:///Set.rsc|(7450,397,<345,0>,<362,54>)
	main([]) at |test-modules:///ConsoleInput.rsc|(124,29,<8,0>,<8,29>)

ok
----
We can also catch the `EmptySet` error. First import the Rascal exceptions (which are also included in `Prelude`)
and `IO`:
[source,rascal-shell-error]
----
rascal>import Exception;
rlib1 = Prelude, rlib2 = |std:///PreludeCompiled.class|
resolveLibOverriding org.rascalmpl.library.Prelude => org.rascalmpl.library.PreludeCompiled
ok
rascal>import IO;
rlib1 = Prelude, rlib2 = |std:///PreludeCompiled.class|
resolveLibOverriding org.rascalmpl.library.Prelude => org.rascalmpl.library.PreludeCompiled
ok
rascal>try println(getOneFrom(S)); catch EmptySet(): println("Cannot apply getOneFrom to empty set");
rlib1 = Prelude, rlib2 = |std:///PreludeCompiled.class|
resolveLibOverriding org.rascalmpl.library.Prelude => org.rascalmpl.library.PreludeCompiled
Cannot apply getOneFrom to empty set
ok
----

.Benefits

.Pitfalls


:leveloffset: +1

:leveloffset: -1