
[[Prelude-Relation]]


[[Prelude-Relation]]
# Relation
:concept: Prelude/Relation
.Usage
`import Relation;`



.Synopsis
Library functions for relations.

.Description

For operators on relations see link:{RascalLang}#Values-Relation[Relation] in the Rascal Language Reference.

The following functions are defined for relations:



* <<Relation-carrier,carrier>>: Return the set of all elements in any tuple in a relation.
      
* <<Relation-carrierR,carrierR>>: A relation restricted to certain element values in tuples.
      
* <<Relation-carrierX,carrierX>>: A relation excluding tuples that contain certain element values.
      
* <<Relation-complement,complement>>: Complement of a relation.
      
* <<Relation-domain,domain>>: Domain of a  relation: a set consisting of the first element of each tuple.
      
* <<Relation-domainR,domainR>>: Relation restricted to certain domain elements.
      
* <<Relation-domainX,domainX>>: Relation excluding certain domain values.
      
* <<Relation-groupDomainByRange,groupDomainByRange>>: Make sets of elements in the domain that relate to the same element in the range.
      
* <<Relation-groupRangeByDomain,groupRangeByDomain>>: Make sets of elements in the range that relate to the same element in the domain.
      
* <<Relation-ident,ident>>: The identity relation.
      
* <<Relation-index,index>>: Indexes a binary relation as a map
      
* <<Relation-invert,invert>>: Invert the tuples in a relation.
      
* <<Relation-range,range>>: The range (i.e., all but the first element of each tuple) of a relation.
      
* <<Relation-rangeR,rangeR>>: Relation restricted to certain range values.
      
* <<Relation-rangeX,rangeX>>: Relation excluding certain range values.
      

[[Relation-carrier]]
## carrier

.Function 
* `set[&T]  carrier (rel[&T,&T] R)`
          * `set[&T]  carrier (rel[&T,&T,&T] R)`
          * `set[&T]  carrier (rel[&T,&T,&T,&T] R)`
          * `set[&T]  carrier (rel[&T,&T,&T,&T,&T] R)`
          


.Synopsis
Return the set of all elements in any tuple in a relation.

.Examples
[source,rascal-shell]
----
rascal>import Relation;
rascal2rvm: Parsing and checking |std:///Relation.rsc|
rascal2rvm: Compiling |std:///Relation.rsc|
r2mu: entering ... Relation
rlib1 = Prelude, rlib2 = |std:///PreludeCompiled.class|
resolveLibOverriding org.rascalmpl.library.Prelude => org.rascalmpl.library.PreludeCompiled
mu2rvm: Compiling module Relation
Compiling |std:///Relation.rsc|: check: 57, compile: 409, total: 466 ms
compile: Writing RVMModule |compressed+home:///bin-console/Relation.rvm.gz|
Removing |compressed+home:///bin-console/ConsoleInput_imports.rvm.gz|
ok
rascal>carrier({<1,10>, <2,20>});
set[int]: {10,1,20,2}
rascal>carrier({<1,10,100,1000>, <2,20,200,2000>});
set[int]: {10,200,20,2,100,1000,1,2000}
----


[[Relation-carrierR]]
## carrierR

.Function 
* `rel[&T,&T] carrierR (rel[&T,&T] R, set[&T] S)`
          * `rel[&T,&T,&T] carrierR (rel[&T,&T,&T] R, set[&T] S)`
          * `rel[&T,&T,&T,&T] carrierR (rel[&T,&T,&T,&T] R, set[&T] S)`
          * `rel[&T,&T,&T,&T,&T] carrierR (rel[&T,&T,&T,&T,&T] R, set[&T] S)`
          


.Synopsis
A relation restricted to certain element values in tuples.

.Description
Returns relation `R` restricted to tuples with elements in set `S`.

.Examples
[source,rascal-shell]
----
rascal>import Relation;
ok
rascal>carrierR({<1,10>, <2,20>, <3,30>}, {10, 1, 20});
rel[int,int]: {<1,10>}
----


[[Relation-carrierX]]
## carrierX

.Function 
* `rel[&T,&T] carrierX (rel[&T,&T] R, set[&T] S)`
          * `rel[&T,&T,&T] carrierX (rel[&T,&T,&T] R, set[&T] S)`
          * `rel[&T,&T,&T,&T] carrierX (rel[&T,&T,&T,&T] R, set[&T] S)`
          * `rel[&T,&T,&T,&T,&T] carrierX (rel[&T,&T,&T,&T,&T] R, set[&T] S)`
          


.Synopsis
A relation excluding tuples that contain certain element values.

.Examples
[source,rascal-shell]
----
rascal>import Relation;
ok
rascal>carrierX({<1,10>, <2,20>, <3,30>}, {10, 1, 20});
rel[int,int]: {<3,30>}
----


[[Relation-complement]]
## complement

.Function 
* `rel[&T0, &T1] complement(rel[&T0, &T1] R)`
          * `rel[&T0, &T1, &T2] complement(rel[&T0, &T1, &T2] R)`
          * `rel[&T0, &T1, &T2, &T3] complement(rel[&T0, &T1, &T2, &T3] R)`
          * `rel[&T0, &T1, &T2, &T3, &T4] complement(rel[&T0, &T1, &T2, &T3, &T4] R)`
          


.Synopsis
Complement of a relation.

.Description
Given a relation `R` a new relation `U` can be constructed that contains
all possible tuples with element values that occur at corresponding tuple positions in `R`.
The function `complement` returns the complement of `R` relative to `U`, in other words: `U - R`.

.Examples
[source,rascal-shell]
----
rascal>import Relation;
ok
----
Declare `R` and compute corresponding `U`:
[source,rascal-shell]
----
rascal>R = {<1,10>, <2, 20>, <3, 30>};
rel[int,int]: {
  <1,10>,
  <2,20>,
  <3,30>
}
rascal>U = domain(R) * range(R);
rel[int,int]: {
  <1,20>,
  <3,20>,
  <2,20>,
  <2,30>,
  <2,10>,
  <1,10>,
  <1,30>,
  <3,10>,
  <3,30>
}
----
Here is the complement of `R` computed in two ways:
[source,rascal-shell]
----
rascal>U - R;
rel[int,int]: {
  <1,20>,
  <3,20>,
  <1,30>,
  <3,10>,
  <2,30>,
  <2,10>
}
rascal>complement({<1,10>, <2, 20>, <3, 30>});
rel[int,int]: {
  <1,20>,
  <3,20>,
  <1,30>,
  <3,10>,
  <2,30>,
  <2,10>
}
----


[[Relation-domain]]
## domain

.Function 
* `set[&T0] domain (rel[&T0,&T1] R)`
          * `set[&T0] domain (rel[&T0,&T1,&T2] R)`
          * `set[&T0] domain (rel[&T0,&T1,&T2,&T3] R)`
          * `set[&T0] domain (rel[&T0,&T1,&T2,&T3,&T4] R)`
          


.Synopsis
Domain of a  relation: a set consisting of the first element of each tuple.

.Examples
[source,rascal-shell]
----
rascal>import Relation;
ok
rascal>domain({<1,10>, <2,20>});
set[int]: {1,2}
rascal>domain({<"mon", 1>, <"tue", 2>});
set[str]: {"tue","mon"}
----


[[Relation-domainR]]
## domainR

.Function 
* `rel[&T0,&T1] domainR (rel[&T0,&T1] R, set[&T0] S)`
          * `rel[&T0,&T1,&T2] domainR (rel[&T0,&T1,&T2] R, set[&T0] S)`
          * `rel[&T0,&T1,&T2,&T3] domainR (rel[&T0,&T1,&T2,&T3] R, set[&T0] S)`
          * `rel[&T0,&T1,&T2,&T3,&T4] domainR (rel[&T0,&T1,&T2,&T3,&T4] R, set[&T0] S)`
          


.Synopsis
Relation restricted to certain domain elements.

.Description
Restriction of a relation `R` to tuples with first element in `S`.

.Examples
[source,rascal-shell]
----
rascal>import Relation;
ok
rascal>domainR({<1,10>, <2,20>, <3,30>}, {3, 1});
rel[int,int]: {
  <1,10>,
  <3,30>
}
----


[[Relation-domainX]]
## domainX

.Function 
* `rel[&T0,&T1] domainX (rel[&T0,&T1] R, set[&T0] S)`
          * `rel[&T0,&T1,&T2] domainX (rel[&T0,&T1,&T2] R, set[&T0] S)`
          * `rel[&T0,&T1,&T2,&T3] domainX (rel[&T0,&T1,&T2,&T3] R, set[&T0] S)`
          * `rel[&T0,&T1,&T2,&T3,&T4] domainX (rel[&T0,&T1,&T2,&T3,&T4] R, set[&T0] S)`
          


.Synopsis
Relation excluding certain domain values.

.Description
Relation `R` excluded tuples with first element in `S`.

.Examples
[source,rascal-shell]
----
rascal>import Relation;
ok
rascal>domainX({<1,10>, <2,20>, <3,30>}, {3, 1});
rel[int,int]: {<2,20>}
----


[[Relation-groupDomainByRange]]
## groupDomainByRange

.Function 
`set[set[&U]] groupDomainByRange(rel[&U dom, &T ran] input)`


.Synopsis
Make sets of elements in the domain that relate to the same element in the range.

.Examples

[source,rascal-shell]
----
rascal>import Relation;
ok
rascal>legs = {<"bird", 2>, <"dog", 4>, <"human", 2>, <"spider", 8>, <"millepede", 1000>, <"crab", 8>, <"cat", 4>};
rel[str,int]: {
  <"crab",8>,
  <"bird",2>,
  <"millepede",1000>,
  <"dog",4>,
  <"spider",8>,
  <"human",2>,
  <"cat",4>
}
rascal>groupDomainByRange(legs);
set[set[str]]: {
  {"human","bird"},
  {"cat","dog"},
  {"spider","crab"},
  {"millepede"}
}
----



[[Relation-groupRangeByDomain]]
## groupRangeByDomain

.Function 
`set[set[&T]] groupRangeByDomain(rel[&U dom, &T ran] input)`


.Synopsis
Make sets of elements in the range that relate to the same element in the domain.

.Description
[source,rascal-shell]
----
rascal>import Relation;
ok
rascal>skins = {<"bird", "feather">, <"dog", "fur">, <"tortoise", "shell">, <"human", "skin">, <"fish", "scale">, <"lizard", "scale">, <"crab", "shell">, <"cat", "fur">};
rel[str,str]: {
  <"fish","scale">,
  <"tortoise","shell">,
  <"lizard","scale">,
  <"human","skin">,
  <"cat","fur">,
  <"crab","shell">,
  <"dog","fur">,
  <"bird","feather">
}
rascal>groupRangeByDomain(skins);
set[set[str]]: {
  {"scale"},
  {"shell"},
  {"skin"},
  {"feather"},
  {"fur"}
}
----



[[Relation-ident]]
## ident

.Function 
`rel[&T, &T] ident (set[&T] S)`


.Synopsis
The identity relation.

.Description
The identity relation for set `S`.

.Examples
[source,rascal-shell]
----
rascal>import Relation;
ok
rascal>ident({"mon", "tue", "wed"});
rel[str,str]: {
  <"tue","tue">,
  <"mon","mon">,
  <"wed","wed">
}
----


[[Relation-index]]
## index

.Function 
`map[&K, set[&V]] index(rel[&K, &V] R)`


.Synopsis
Indexes a binary relation as a map

.Description
Converts a binary relation to a map of the domain to a set of the range.

.Examples
[source,rascal-shell]
----
rascal>import Relation;
ok
rascal>index({<1,10>, <2,20>, <3,30>, <30,10>});
map[int, set[int]]: (
  1:{10},
  3:{30},
  2:{20},
  30:{10}
)
----



[[Relation-invert]]
## invert

.Function 
* `rel[&T1, &T0] invert (rel[&T0, &T1] R)`
          * `rel[&T2, &T1, &T0] invert (rel[&T0, &T1, &T2] R)`
          * `rel[&T3, &T2, &T1, &T0] invert (rel[&T0, &T1, &T2, &T3] R)`
          * `rel[&T4, &T3, &T2, &T1, &T0] invert (rel[&T0, &T1, &T2, &T3, &T4] R)`
          


.Synopsis
Invert the tuples in a relation.

.Examples
[source,rascal-shell]
----
rascal>import Relation;
ok
rascal>invert({<1,10>, <2,20>});
rel[int,int]: {
  <10,1>,
  <20,2>
}
----


[[Relation-range]]
## range

.Function 
* `set[&T1] range (rel[&T0,&T1] R)`
          * `rel[&T1,&T2] range (rel[&T0,&T1, &T2] R)`
          * `rel[&T1,&T2,&T3] range (rel[&T0,&T1,&T2,&T3] R)`
          * `rel[&T1,&T2,&T3,&T4] range (rel[&T0,&T1,&T2,&T3,&T4] R)`
          


.Synopsis
The range (i.e., all but the first element of each tuple) of a relation.

.Examples
[source,rascal-shell]
----
rascal>import Relation;
ok
rascal>range({<1,10>, <2,20>});
set[int]: {10,20}
rascal>range({<"mon", 1>, <"tue", 2>});
set[int]: {1,2}
----


[[Relation-rangeR]]
## rangeR

.Function 
`rel[&T0,&T1] rangeR (rel[&T0,&T1] R, set[&T2] S)`


.Synopsis
Relation restricted to certain range values.

.Description
Restriction of binary relation `R` to tuples with second element in set `S`.

.Examples
[source,rascal-shell]
----
rascal>import Relation;
ok
rascal>rangeR({<1,10>, <2,20>, <3,30>}, {30, 10});
rel[int,int]: {
  <1,10>,
  <3,30>
}
----


[[Relation-rangeX]]
## rangeX

.Function 
`rel[&T0,&T1] rangeX (rel[&T0,&T1] R, set[&T2] S)`

 
.Synopsis
Relation excluding certain range values.

.Description
Restriction of binary relation `R` to tuples with second element not in set `S`.

.Examples
[source,rascal-shell]
----
rascal>import Relation;
ok
rascal>rangeX({<1,10>, <2,20>, <3,30>}, {30, 10});
rel[int,int]: {<2,20>}
----


:leveloffset: +1

:leveloffset: -1