
[[Relation-Subscription]]
# Relation Subscription
:concept: Expressions/Values/Relation/Subscription

.Synopsis
Indexing of a relation via tuple values.

.Index
[ ]

.Syntax

#  `_Exp_0_ [ _Exp~1~_, _Exp~2~_, ... _Exp~n~_]`

#  `_Exp_0_ [ _Exp~1~_]`

.Types
## Variant 1

[cols="20,20,20,15,25"]
|====
| `_Exp_0_`                         | `_Exp~1~_` | `_Exp~2~_` | ... | `_Exp_0_ [ _Exp~1~_, _Exp~2~_, ... ]` 

| `rel[_T~1~_, _T~2~_, ... _T~m~_]`    | `int`     |  `int`    | ... | `rel[_T~n~_, _T~n+1~_, ... _T~m~_]` 
|====

## Variant 2

|====
| `_Exp~0~_`                         | `_Exp~1~_`     | `_Exp~0~_ [ _Exp~1~_ ]`            

| `rel[_T~1~_, _T~2~_, ... _T~m~_]`    | `set[_T~1~_]`  | `rel[_T~2~_, _T~2~_, ... _T~m~_]`   
|====

.Function

.Description
Relation resulting from subscription of a relation _Exp_~0~.

## Variant 1

Subscription with the index values of _Exp_~1~, _Exp_~2~, .... 
The result is a relation with all tuples that have these index values as first elements 
with the index values removed from the tuple. 
If the resulting tuple has only a single element, a set is returned instead of a relation. 
A wildcard `_` as index value matches all possible values at that index position.

## Variant 2

Subscription with a set of the index values of _Exp_~1~.
The result is a relation with all tuples that have these index values as first element
with the index values removed from the tuple. 

.Examples
[source,rascal-shell]
----
rascal>R = {<1,10>, <2,20>, <1,11>, <3,30>, <2,21>};
rel[int,int]: {
  <1,10>,
  <2,20>,
  <3,30>,
  <2,21>,
  <1,11>
}
rascal>R[1];
set[int]: {10,11}
rascal>R[{1}];
set[int]: {10,11}
rascal>R[{1, 2}];
set[int]: {10,20,11,21}
rascal>RR = {<1,10,100>,<1,11,101>,<2,20,200>,<2,22,202>,
>>>>>>>              <3,30,300>};
rel[int,int,int]: {
  <1,10,100>,
  <3,30,300>,
  <1,11,101>,
  <2,20,200>,
  <2,22,202>
}
rascal>RR[1];
rel[int,int]: {
  <10,100>,
  <11,101>
}
rascal>RR[1,_];
set[int]: {100,101}
----
Introduce a relation with economic data and assign it to `GDP`:
[source,rascal-shell]
----
rascal>rel[str country, int year, int amount] GDP =
>>>>>>>{<"US", 2008, 14264600>, <"EU", 2008, 18394115>,
>>>>>>> <"Japan", 2008, 4923761>, <"US", 2007, 13811200>, 
>>>>>>> <"EU", 2007, 13811200>, <"Japan", 2007, 4376705>};
rel[str,int,int]: {
  <"EU",2007,13811200>,
  <"US",2007,13811200>,
  <"Japan",2007,4376705>,
  <"US",2008,14264600>,
  <"Japan",2008,4923761>,
  <"EU",2008,18394115>
}
----
and then retrieve the information for the index `"Japan"`:
[source,rascal-shell]
----
rascal>GDP["Japan"];
rel[int,int]: {
  <2008,4923761>,
  <2007,4376705>
}
----
or rather for the indices `"Japan"` and `2008`:
[source,rascal-shell]
----
rascal>GDP["Japan", 2008];
set[int]: {4923761}
----

.Benefits

.Pitfalls


:leveloffset: +1

:leveloffset: -1