
[[Prelude-Boolean]]


[[Prelude-Boolean]]
# Boolean
:concept: Prelude/Boolean
.Usage
`import Boolean;`


.Synopsis
Library functions for Booleans.

.Description

For operators on Boolean values see link:{RascalLang}#Values-Boolean[Boolean] in the Rascal Language Reference.

The following functions are defined for Booleans:


[[Boolean-arbBool]]
## arbBool

.Function 
`bool arbBool()`

.Synopsis
Return an arbitrary Boolean value.

.Examples
[source,rascal-shell]
----
rascal>import Boolean;
ok
rascal>arbBool();
bool: false
rascal>arbBool();
bool: true
rascal>arbBool();
bool: true
----

.Benefits
`arbInt` is a convenient generator for arbitrary binary choices.

[[Boolean-fromString]]
## fromString

.Function 
`bool fromString(str s)`

.Synopsis
Convert the strings "true" or "false" to a bool.

[[Boolean-toInt]]
## toInt

.Function 
`int toInt(bool b)`

.Synopsis
Convert a Boolean value to integer.

.Description
Maps `true` to `1` and `false` to `0`.

.Examples
[source,rascal-shell]
----
rascal>import Boolean;
ok
rascal>toInt(true);
int: 1
rascal>toInt(false);
int: 0
----

[[Boolean-toReal]]
## toReal

.Function 
`real toReal(bool b)`

.Synopsis
Convert Boolean value to real.

.Description
Maps `true` to `1.0` and `false` to `0.0`.

.Examples
[source,rascal-shell]
----
rascal>import Boolean;
ok
rascal>toReal(true);
real: 1.0
rascal>toReal(false);
real: 0.0
----

[[Boolean-toString]]
## toString

.Function 
`str toString(bool b)`

.Synopsis
Convert Boolean value to string.

.Description
Maps `true` to `"true"` and `false` to `"false"`.

.Examples
[source,rascal-shell]
----
rascal>import Boolean;
ok
rascal>toString(true);
str: "true"
rascal>toString(false);
str: "false"
----

:leveloffset: +1

:leveloffset: -1