
[[MeasuringJava-MeasuringClasses]]
# Measuring Classes
:concept: Metrics/MeasuringJava/MeasuringClasses

.Synopsis


.Syntax

.Types

.Function
       
.Usage

.Description

.Examples

[source,rascal-shell]
----
----
First we import the basic data types for representing Java. The model is called _M3_, and its definition is split acros a generic
language independent module called [Rascal:analysis/m3/Core] and a Java specific part called [Rascal:lang/java/m3/Core]. Have a look at the documentation 
of these modules later. For now we will go through using them in a few examples.
[source,rascal-shell]
----
rascal>import lang::java::m3::Core;
rascal2rvm: Parsing and checking |std:///analysis/m3/AST.rsc|
rascal2rvm: Compiling |std:///analysis/m3/AST.rsc|
r2mu: entering ... analysis::m3::AST
mu2rvm: Compiling module analysis::m3::AST
Compiling |std:///analysis/m3/AST.rsc|: check: 11, compile: 35, total: 46 ms
compile: Writing RVMModule |compressed+home:///bin-console/analysis/m3/AST.rvm.gz|
rascal2rvm: Parsing and checking |std:///analysis/m3/Core.rsc|
rascal2rvm: Compiling |std:///analysis/m3/Core.rsc|
r2mu: entering ... analysis::m3::Core
mu2rvm: Compiling module analysis::m3::Core
Compiling |std:///analysis/m3/Core.rsc|: check: 37, compile: 927, total: 964 ms
compile: Writing RVMModule |compressed+home:///bin-console/analysis/m3/Core.rvm.gz|
rascal2rvm: Parsing and checking |std:///lang/java/m3/TypeSymbol.rsc|
rascal2rvm: Compiling |std:///lang/java/m3/TypeSymbol.rsc|
r2mu: entering ... lang::java::m3::TypeSymbol
mu2rvm: Compiling module lang::java::m3::TypeSymbol
Compiling |std:///lang/java/m3/TypeSymbol.rsc|: check: 10, compile: 33, total: 43 ms
compile: Writing RVMModule |compressed+home:///bin-console/lang/java/m3/TypeSymbol.rvm.gz|
rascal2rvm: Parsing and checking |std:///lang/java/m3/AST.rsc|
rascal2rvm: Compiling |std:///lang/java/m3/AST.rsc|
r2mu: entering ... lang::java::m3::AST
rlib1 = lang.java.m3.internal.EclipseJavaCompiler, rlib2 = |std:///lang/java/m3/internal/EclipseJavaCompilerCompiled.class|
resolveLibOverriding org.rascalmpl.library.lang.java.m3.internal.EclipseJavaCompiler => org.rascalmpl.library.lang.java.m3.internal.EclipseJavaCompiler
mu2rvm: Compiling module lang::java::m3::AST
Compiling |std:///lang/java/m3/AST.rsc|: check: 58, compile: 3195, total: 3253 ms
compile: Writing RVMModule |compressed+home:///bin-console/lang/java/m3/AST.rvm.gz|
rascal2rvm: Parsing and checking |std:///lang/java/m3/Registry.rsc|
rascal2rvm: Compiling |std:///lang/java/m3/Registry.rsc|
r2mu: entering ... lang::java::m3::Registry
mu2rvm: Compiling module lang::java::m3::Registry
Compiling |std:///lang/java/m3/Registry.rsc|: check: 18, compile: 571, total: 589 ms
compile: Writing RVMModule |compressed+home:///bin-console/lang/java/m3/Registry.rvm.gz|
rascal2rvm: Parsing and checking |std:///analysis/m3/TypeSymbol.rsc|
rascal2rvm: Compiling |std:///analysis/m3/TypeSymbol.rsc|
r2mu: entering ... analysis::m3::TypeSymbol
mu2rvm: Compiling module analysis::m3::TypeSymbol
Compiling |std:///analysis/m3/TypeSymbol.rsc|: check: 6, compile: 528, total: 534 ms
compile: Writing RVMModule |compressed+home:///bin-console/analysis/m3/TypeSymbol.rvm.gz|
rascal2rvm: Parsing and checking |std:///lang/java/m3/Core.rsc|
rascal2rvm: Compiling |std:///lang/java/m3/Core.rsc|
r2mu: entering ... lang::java::m3::Core
rlib1 = lang.java.m3.internal.EclipseJavaCompiler, rlib2 = |std:///lang/java/m3/internal/EclipseJavaCompilerCompiled.class|
resolveLibOverriding org.rascalmpl.library.lang.java.m3.internal.EclipseJavaCompiler => org.rascalmpl.library.lang.java.m3.internal.EclipseJavaCompiler
mu2rvm: Compiling module lang::java::m3::Core
Compiling |std:///lang/java/m3/Core.rsc|: check: 75, compile: 2411, total: 2486 ms
compile: Writing RVMModule |compressed+home:///bin-console/lang/java/m3/Core.rvm.gz|
rascal2rvm: Parsing and checking |std:///analysis/m3/Registry.rsc|
rascal2rvm: Compiling |std:///analysis/m3/Registry.rsc|
r2mu: entering ... analysis::m3::Registry
mu2rvm: Compiling module analysis::m3::Registry
Compiling |std:///analysis/m3/Registry.rsc|: check: 20, compile: 577, total: 597 ms
compile: Writing RVMModule |compressed+home:///bin-console/analysis/m3/Registry.rvm.gz|
rascal2rvm: Parsing and checking |std:///util/FileSystem.rsc|
rascal2rvm: Compiling |std:///util/FileSystem.rsc|
r2mu: entering ... util::FileSystem
mu2rvm: Compiling module util::FileSystem
Compiling |std:///util/FileSystem.rsc|: check: 14, compile: 59, total: 73 ms
compile: Writing RVMModule |compressed+home:///bin-console/util/FileSystem.rvm.gz|
Removing |compressed+home:///bin-console/ConsoleInput_imports.rvm.gz|
ok
----
Then we import the API for extracting an M3 model from an Eclipse project. 
[source,rascal-shell]
----
rascal>import lang::java::jdt::m3::Core;
[error] Cannot import module lang::java::jdt::m3::Core AT |std:///experiments/Compiler/Compile.rsc|(0,51,<1,0>,<1,51>)
----
Calling the following function generates an enormous value representing everything the Eclipse Java compiler knows about this project:
[source,rascal-shell]
----
rascal>myModel = createM3FromEclipseProject(|project://example-project|);
[error] Name createM3FromEclipseProject is not in scope
----
Next, let's focus on the _containment_ relation. This defines what parts of the source code are parts of which other parts:
[source,rascal-shell]
----
rascal>myModel@containment
[error] Name myModel is not in scope
----
As you can read, classes contain methods, methods contain variables, etc. Classes could also contain other classes (nested classes), and methods can even contain classes (anonymous classes). Let's focus on a specific class, and project what it contains from the relation:
[source,rascal-shell]
----
rascal>myModel@containment[|java+class:///HelloWorld|]
[error] Name myModel is not in scope
----
Let's filter the methods:
[source,rascal-shell]
----
rascal>helloWorldMethods = [ e | e <- myModel@containment[|java+class:///HelloWorld|], e.scheme == "java+method"];
[error] Name myModel is not in scope
----
And we are ready to compute our first metric. How many methods does this class contain?
[source,rascal-shell]
----
rascal>import List;
ok
rascal>size(helloWorldMethods)
[error] Name helloWorldMethods is not in scope
----
No magic applied! It is just a little query on a model that knows everything about the code. Let's generalize and compute the number of methods for all classes in one big expression. First a function to compute the number for a given class:
[source,rascal-shell]
----
rascal>int numberOfMethods(loc cl, M3 model) = size([ m | m <- model@containment[cl], isMethod(m)]);
ok
----
then we apply this new function to give us a map from classes to integers:
[source,rascal-shell]
----
rascal>map[loc class, int methodCount] numberOfMethodsPerClass = (cl:numberOfMethods(cl, myModel) | <cl,_> <- myModel@containment, isClass(cl));
[error] Name myModel is not in scope
[error] Name myModel is not in scope
----
how about the number of fields?
[source,rascal-shell]
----
rascal>int numberOfFields(loc cl, M3 model) = size([ m | m <- model@containment[cl], isField(m)]);
ok
rascal>map[loc class, int fieldCount] numberOfFieldsPerClass = (cl:numberOfFields(cl, myModel) | <cl,_> <- myModel@containment, isClass(cl));
[error] Name myModel is not in scope
[error] Name myModel is not in scope
----
what is the ratio between fields and methods for each class?
[source,rascal-shell]
----
rascal>(cl : (numberOfFieldsPerClass[cl] * 1.0) / (numberOfMethodsPerClass[cl] * 1.0) | cl <- classes(myModel))
[error] Name numberOfMethodsPerClass is not in scope
[error] Name numberOfFieldsPerClass is not in scope
[error] Name myModel is not in scope
----

.Benefits

.Pitfalls


:leveloffset: +1

:leveloffset: -1