
[[Combined-Manual]]
# Manual
:concept: Languages/Exp/Combined/Manual

.Synopsis
An Exp evaluator that uses a manually written conversion from parse tree to abstract syntax tree.

.Syntax

.Types

.Function

.Description

.Examples

First we define a `parse` function for Exp:

[source,rascal]
----
include::{LibDir}demo/lang/Exp/Combined/Manual/Parse.rsc[tags=module]
----

and test it:
[source,rascal-shell]
----
rascal>import demo::lang::Exp::Combined::Manual::Parse;
rascal2rvm: Parsing and checking |std:///demo/lang/Exp/Combined/Manual/Parse.rsc|
rascal2rvm: Compiling |std:///demo/lang/Exp/Combined/Manual/Parse.rsc|
r2mu: entering ... demo::lang::Exp::Combined::Manual::Parse
mu2rvm: Compiling module demo::lang::Exp::Combined::Manual::Parse
Compiling |std:///demo/lang/Exp/Combined/Manual/Parse.rsc|: check: 12, compile: 1101, total: 1113 ms
compile: Writing RVMModule |compressed+home:///bin-console/demo/lang/Exp/Combined/Manual/Parse.rvm.gz|
Removing |compressed+home:///bin-console/ConsoleInput_imports.rvm.gz|
ok
rascal>parseExp("2+3");
Exp: (Exp) `2+3`
----

Next, we define a `load` function:
[source,rascal]
----
include::{LibDir}demo/lang/Exp/Combined/Manual/Load.rsc[tags=module]
----

Some comments:

<1> We reuse the previously defined concrete syntax with layout.
<2> We also reuse the previously defined abstract syntax.
<3> Import the `Parse` module defined above.
<4> The top level `load` function that converts a string to an abstract syntax tree.
<5> The conversion from parse tree to abstract syntax tree start here. Note that we
    explicitly use `demo::lang::Exp::Concrete::WithLayout::Syntax::Exp` in these
    rules to distinguish from `demo::lang::Exp::Abstract::Syntax::Exp`.


Let's try it:
[source,rascal-shell]
----
rascal>import demo::lang::Exp::Combined::Manual::Load;
rascal2rvm: Parsing and checking |std:///demo/lang/Exp/Combined/Manual/Load.rsc|
rascal2rvm: Compiling |std:///demo/lang/Exp/Combined/Manual/Load.rsc|
r2mu: entering ... demo::lang::Exp::Combined::Manual::Load
mu2rvm: Compiling module demo::lang::Exp::Combined::Manual::Load
Compiling |std:///demo/lang/Exp/Combined/Manual/Load.rsc|: check: 17, compile: 207, total: 224 ms
compile: Writing RVMModule |compressed+home:///bin-console/demo/lang/Exp/Combined/Manual/Load.rvm.gz|
Removing |compressed+home:///bin-console/ConsoleInput_imports.rvm.gz|
ok
rascal>loadExp("2+3");
Exp: add(
  con(2),
  con(3))
----


What remains is to write the interpreter using the above components:
[source,rascal]
----
include::{LibDir}demo/lang/Exp/Combined/Manual/Eval.rsc[tags=module]
----

                
Here is how it works:
[source,rascal-shell]
----
rascal>import demo::lang::Exp::Combined::Manual::Eval;
rascal2rvm: Parsing and checking |std:///demo/lang/Exp/Combined/Manual/Eval.rsc|
rascal2rvm: Compiling |std:///demo/lang/Exp/Combined/Manual/Eval.rsc|
r2mu: entering ... demo::lang::Exp::Combined::Manual::Eval
mu2rvm: Compiling module demo::lang::Exp::Combined::Manual::Eval
Compiling |std:///demo/lang/Exp/Combined/Manual/Eval.rsc|: check: 16, compile: 172, total: 188 ms
compile: Writing RVMModule |compressed+home:///bin-console/demo/lang/Exp/Combined/Manual/Eval.rvm.gz|
Removing |compressed+home:///bin-console/ConsoleInput_imports.rvm.gz|
ok
rascal>eval("2+3");
int: 5
----

.Benefits

.Pitfalls


:leveloffset: +1

:leveloffset: -1