
[[Common-WordCount]]
# Word Count
:concept: Common/WordCount

.Synopsis
Counting words in strings.

.Syntax

.Types

.Function

.Description

.Examples

The purpose of WordCount is to count the number of _words_ in a list of lines (strings).
A word is here defined as one or more letters (lowercase or uppercase), digits and the underscore character (`_`).

We split the problem in two parts:

*  Count the words in a single line. We explore three ways to do this in an imperative (<<CountInLine1>>], <<CountInLine2>>)
  and a functional style (<<CountInLine3>>).
*  Next we apply the single line counter to all the lines.


`wordCount` is a function with two arguments:
*  A list of lines.
*  A function that returns the number of words in a line.


The main task of `wordCount` is to loop over all lines and to add the word counts per line.


[source,rascal]
----
include::{LibDir}demo/common/WordCount/WordCount.rsc[tags=module]
----

                
<1> An link:{RascalLang}#Comprehensions-Enumerator[enumerator] is used to generated all the lines in the list of lines.
<2> The argument function `countInLine` is applied to count the number of words in each line.

Let's now do some experiments using the <<Jabberwocky>> poem by Lewis Carrol as input.

[source,rascal-shell]
----
rascal>import demo::common::WordCount::WordCount;
ok
rascal>import demo::common::WordCount::CountInLine1;
ok
rascal>import demo::common::WordCount::CountInLine2;
ok
rascal>import demo::common::WordCount::CountInLine3;
ok
rascal>import demo::common::WordCount::Jabberwocky;
ok
rascal>wordCount(Jabberwocky, countInLine1);
int: 216
rascal>wordCount(Jabberwocky, countInLine2);
int: 216
rascal>wordCount(Jabberwocky, countInLine3);
int: 216
----
It is satisfactory that the three ways of counting words all yield the same result.

If you are into one-liners, we can include everything you learned from this example
in the following alternative `wordCount2` function:
[source,rascal-shell]
----
rascal>int wordCount2(list[str] lines) = (0 | it + (0 | it + 1 | /\w+/ := line) | str line <- lines);
ok
rascal>wordCount2(Jabberwocky);
int: 216
----
Explain what is going on in this function.
[source,rascal-shell]
----
----


.Benefits

.Pitfalls


:leveloffset: +1
include::CountInLine1/CountInLine1.adoc[CountInLine1]

include::CountInLine2/CountInLine2.adoc[CountInLine2]

include::CountInLine3/CountInLine3.adoc[CountInLine3]

include::Jabberwocky/Jabberwocky.adoc[Jabberwocky]


:leveloffset: -1