
[[Dynamic-PathNotFound]]
# PathNotFound
:concept: Dynamic/PathNotFound

.Synopsis
A requested path name cannot be found.

.Syntax

.Types

.Function
.Usage

.Description
The `PathNotFound` error is generated in all cases where access to the requested location is impossible.
This includes:

*  A non-existing path.
*  A non-existing file.
*  Insufficient rights to read/write the file.


Remedies:

*  Check that the path is correct.
*  Check that the resource exists.
*  When using the `file` scheme:
**  Check that you have read/write access to the file.
**  When you use an absolute path name, your location should always start with 3 slash (`/`) characters:
***  `|file:///users/paulklint/file.txt|` is correct.
***  `|file://users/paulklint/file.txt|` gives a `PathNotFound` error.
**  When you use a relative path name, make sure that it is relative to the directory from which Rascal was started.
*  Catch the `PathNotFound` yourself, see [Rascal:TryCatch].

.Examples
[source,rascal-shell-error]
----
rascal>import IO;
ok
----
Reading a non-existing URI gives an error:
[source,rascal-shell-error]
----
rascal>readFile(|http://www.cwi.nl/does_not_exist|);
PathNotFound(|http://www.cwi.nl/does_not_exist|)
Call stack (most recent first):
	readFile(|http://www.cwi.nl/does_not_exist|, {}) at |std:///IO.rsc|(12600,1747,<540,0>,<576,43>)
	main([]) at |test-modules:///ConsoleInput.rsc|(47,44,<4,15>,<4,59>)

ok
----
Trying to write to a file for which we do not have write access (don't run this as superuser!) als gives an error:
[source,rascal-shell-error]
----
rascal>writeFile(|file:///etc/passwd|, "A BAD idea!");
PathNotFound(|file:///etc/passwd|)
Call stack (most recent first):
	writeFile(|file:///etc/passwd|, ["A BAD idea!"], {}) at |std:///IO.rsc|(16188,595,<637,0>,<653,43>)
	main([]) at |test-modules:///ConsoleInput.rsc|(47,46,<4,15>,<4,61>)

ok
----

.Benefits

.Pitfalls


:leveloffset: +1

:leveloffset: -1