
[[Pico-Load]]
# Load
:concept: Languages/Pico/Load

.Synopsis
Convert a Pico parse tree into a Pico abstract syntax tree.

.Syntax

.Types

.Function
       
.Usage

.Description

.Examples
The mapping between parse tree and abstract sybtax tree is achieved as follows:
[source,rascal]
----
include::{LibDir}demo/lang/Pico/Load.rsc[tags=module]
----

                
Notes:

*  The function `load` takes a string as argument (supposedly the source code of a Pico program) and returns a value of type `PROGRAM`,
the abstract syntax tree of the input program. In case the input program is syntactically incorrect, a `ParseError` exception will be thrown,
see link:{Libraries}#Prelude-RunTimeException[RuntimeException].

*  `parse(#Program, txt)`: parse `txt` according to the non-terminal `Program`. Note that `#Program` is a _reified type_, i.e., the type `Program` is represented as an ordinary Rascal value and passed as argument to the `parse` function,
see link:{RascalLang}#Values-ReifiedTypes[reified types].
The `parse` function returns a parse tree of the input program.

*  `implode(#PROGRAM, parse(#Program, txt))`: transform the parse returned by `parse` into an abstract syntax tree of type `PROGRAM`. The [$Rascal:implode] function performs the automatic mapping between elements in the parse tree and their counterpart in the abstract syntax.


The function `load` can be used as follows:
[source,rascal-shell]
----
rascal>import demo::lang::Pico::Load;
ok
rascal>load("begin declare x : natural; x := 3 end");
PROGRAM: program(
  [decl(
      "x",
      natural()[
        @location=|unknown:///|(18,7,<1,18>,<1,25>),
        @comments=()
      ])[
      @location=|unknown:///|(14,11,<1,14>,<1,25>),
      @comments=()
    ]],
  [asgStat(
      "x",
      natCon(3)[
        @location=|unknown:///|(32,1,<1,32>,<1,33>),
        @comments=()
      ])[
      @location=|unknown:///|(27,6,<1,27>,<1,33>),
      @comments=()
    ]])[
  @location=|unknown:///|(0,37,<1,0>,<1,37>),
  @comments=()
]
----

Observe how the various parts of the abstract syntax tree are annotated with location attributes.

.Benefits

.Pitfalls


:leveloffset: +1

:leveloffset: -1