
[[graphs-LabeledGraph]]


[[graphs-LabeledGraph]]
# LabeledGraph
:concept: analysis/graphs/LabeledGraph
.Usage
`import analysis::graphs::LabeledGraph;`



* <<LabeledGraph-LGraph,LGraph>>: 
* <<LabeledGraph-bottom,bottom>>: Return the bottom nodes of a LGraph.
      
* <<LabeledGraph-predecessors,predecessors>>: The predecessors of a single node in a LGraph.
      
* <<LabeledGraph-reach,reach>>: Reachability from a given start set of nodes.
      
* <<LabeledGraph-reachR,reachR>>: Reachability from given start set of nodes with restrictions.
      
* <<LabeledGraph-reachX,reachX>>: Reachability from given start set of nodes with exclusions.
      
* <<LabeledGraph-successors,successors>>: The successors of a single node in a LGraph.
      
* <<LabeledGraph-top,top>>: Return the top nodes of a LGraph.
      

[[LabeledGraph-LGraph]]
## LGraph
.Types
[source,rascal]
----
alias LGraph[&T,&L] = rel[&T from, &L label, &T to];
----

[[LabeledGraph-bottom]]
## bottom

.Function 
`set[&T] bottom(LGraph[&T,&L] G)`


.Synopsis
Return the bottom nodes of a LGraph.



[[LabeledGraph-predecessors]]
## predecessors

.Function 
`set[&T] predecessors(LGraph[&T,&L] G, &T From)`


.Synopsis
The predecessors of a single node in a LGraph.



[[LabeledGraph-reach]]
## reach

.Function 
`set[&T] reach(LGraph[&T,&L] G, set[&T] Start)`


.Synopsis
Reachability from a given start set of nodes.



[[LabeledGraph-reachR]]
## reachR

.Function 
`set[&T] reachR(LGraph[&T,&L] G, set[&T] Start, set[&T] Restr)`


.Synopsis
Reachability from given start set of nodes with restrictions.



[[LabeledGraph-reachX]]
## reachX

.Function 
`set[&T] reachX(LGraph[&T,&L] G, set[&T] Start, set[&T] Excl)`


.Synopsis
Reachability from given start set of nodes with exclusions.



[[LabeledGraph-successors]]
## successors

.Function 
`set[&T] successors(LGraph[&T, &L] G, &T From)`


.Synopsis
The successors of a single node in a LGraph.



[[LabeledGraph-top]]
## top

.Function 
`set[&T] top(LGraph[&T,&L] G)`


.Synopsis
Return the top nodes of a LGraph.



:leveloffset: +1

:leveloffset: -1