
[[Common-CountConstructors]]
# Count Constructors
:concept: Common/CountConstructors

.Synopsis
Generic function that can count constructors in a value of any algebraic data type.

.Syntax

.Types

.Function

.Description
In <<ColoredTrees>>, we have seen a function that can count the number of red nodes in a `ColoredTree`.
Is it possible to define a function that can count constructors in a value of any algerbaic data type?

We exploit the subtype relation (see link:{RascalLang}#Concepts-StaticTyping[Static Typing]) 
between link:{RascalLang}#Declrations-AlgebraicDataType[algebraic data types]s 
and the type link:{RascalLang}#Values-Node[node] to achieve this.

In real applications this becomes relevant when counting, for instance, statement types in programs.

.Examples

[source,rascal]
----
include::{LibDir}demo/common/CountConstructors.rsc[tags=module]
----

                
Two data types are introduced `ColoredTree` and `Hand` together
with an example value of each (`CT`, respectively, `H`).

<1> The function `count` is defined.

<2> Introduces an empty map to maintain the frequencies.
<3> Defines a visit of argument `N`; it traverses the complete value of `N`.
<4> Defines the case that we encounter a node and we update its frequency count.
  First the name of the constructor is retrieved (using link:{Libraries}#Node-getName[getName]) and then the
  frequency is updated. The link:{RascalLang}#Assignment-IsDefined[isDefined] operator is used to provide a default value of 0 when
  the name was not yet in the map.
<5> The map `freq` is returned as result.
<6> Defines a variant `countRelevant`; it gets is an extra argument of relevant constructors
names that is used to filter the map that is returned by `count` using link:{Libraries}#Map-domainR[domainR].

[source,rascal-shell]
----
rascal>import demo::common::CountConstructors;
ok
rascal>count(CT);
map[str, int]: ("red":2,"leaf":5,"black":2)
rascal>count(H);
map[str, int]: ("six":1,"ace":1,"two":1,"hearts":2,"spades":1,"hand":1,"diamonds":1,"jack":1)
rascal>countRelevant(H, {"hearts", "spades"});
map[str, int]: ("hearts":2,"spades":1)
----

.Benefits

.Pitfalls


:leveloffset: +1

:leveloffset: -1