
[[Prelude-Map]]


[[Prelude-Map]]
# Map
:concept: Prelude/Map
.Usage
`import Map;`



.Synopsis
Library functions for maps.

.Description

For operators on maps see link:{RascalLang}#Values-Map[Map] in the Rascal Language Reference.

The following functions are defined for maps:



* <<Map-delete,delete>>: Delete a key from a map.
      
* <<Map-domain,domain>>: Determine the domain (set of keys) of a map.
      
* <<Map-domainR,domainR>>: Map restricted to certain keys.
      
* <<Map-domainX,domainX>>: Map with certain keys excluded.
      
* <<Map-getOneFrom,getOneFrom>>: Get a n arbitrary key from a map.
      
* <<Map-invert,invert>>: Invert the (key,value) pairs in a map.
      
* <<Map-invertUnique,invertUnique>>: Invert the (key,value) pairs in a map.
      
* <<Map-isEmpty,isEmpty>>: Test whether a map is empty.
      
* <<Map-itoString,itoString>>: Convert a map to a indented string.
      
* <<Map-mapper,mapper>>: Apply a function to all (key, value) pairs in a map.
      
* <<Map-range,range>>: The range (set of values that correspond to its keys) of a map.
      
* <<Map-rangeR,rangeR>>: Map restricted to certain values in (key,values) pairs.
      
* <<Map-rangeX,rangeX>>: Map with certain values in (key,value) pairs excluded.
      
* <<Map-size,size>>: Number of (key, value) pairs in a map.
      
* <<Map-toList,toList>>: Convert a map to a list of tuples.
      
* <<Map-toRel,toRel>>: Convert a map to a relation.
      
* <<Map-toString,toString>>: Convert a map to a string.
      

[[Map-delete]]
## delete

.Function 
`map[&K,&V] delete(map[&K,&V] m, &K k)`


.Synopsis
Delete a key from a map.

.Description
Returns the map `m` minus the key `k`.

.Examples
[source,rascal-shell]
----
rascal>import Map;
ok
rascal>delete(("apple":1,"pear":2), "apple");
map[str, int]: ("pear":2)
----



[[Map-domain]]
## domain

.Function 
`set[&K] domain(map[&K, &V] M)`


.Synopsis
Determine the domain (set of keys) of a map.

.Description
Returns the domain (set of keys) of map `M`.

.Examples
[source,rascal-shell]
----
rascal>import Map;
ok
rascal>domain(("apple": 1, "pear": 2));
set[str]: {"pear","apple"}
----



[[Map-domainR]]
## domainR

.Function 
`map[&K, &V] domainR(map[&K, &V] M, set[&K] S)`


.Synopsis
Map restricted to certain keys.

.Description
Return the map `M` restricted to pairs with key in `S`.

.Examples
[source,rascal-shell]
----
rascal>import Map;
ok
rascal>domainR(("apple": 1, "pear": 2, "orange": 3), {"apple", "pear"});
map[str, int]: ("pear":2,"apple":1)
----



[[Map-domainX]]
## domainX

.Function 
`map[&K, &V] domainX(map[&K, &V] M, set[&K] S)`


.Synopsis
Map with certain keys excluded.

.Description
Return the map `M` restricted to pairs with key not in `S`.

.Examples
[source,rascal-shell]
----
rascal>import Map;
ok
rascal>domainX(("apple": 1, "pear": 2, "orange": 3), {"apple", "pear"});
map[str, int]: ("orange":3)
----



[[Map-getOneFrom]]
## getOneFrom

.Function 
`&K getOneFrom(map[&K, &V] M)`


.Synopsis
Get a n arbitrary key from a map.

.Description
Returns an arbitrary key of map `M`.

.Examples
[source,rascal-shell]
----
rascal>import Map;
ok
rascal>getOneFrom(("apple": 1, "pear": 2, "pineapple": 3));
str: "pineapple"
rascal>getOneFrom(("apple": 1, "pear": 2, "pineapple": 3));
str: "apple"
rascal>getOneFrom(("apple": 1, "pear": 2, "pineapple": 3));
str: "apple"
----



[[Map-invert]]
## invert

.Function 
`map[&V, set[&K]] invert(map[&K, &V] M)`


.Synopsis
Invert the (key,value) pairs in a map.

.Description
Returns inverted map in which each value in the old map `M` is associated with a set of key values from the old map.
Also see <<invertUnique>>.

.Examples
[source,rascal-shell]
----
rascal>import Map;
ok
rascal>invert(("apple": 1, "pear": 2, "orange": 1));
map[int, set[str]]: (
  1:{"orange","apple"},
  2:{"pear"}
)
----



[[Map-invertUnique]]
## invertUnique

.Function 
`map[&V, &K] invertUnique(map[&K, &V] M)`


.Synopsis
Invert the (key,value) pairs in a map.

.Description
Returns a map with key and value inverted; the result should be a map.
If the initial map contains duplicate values,
the `MultipleKey` exception is raised since
an attempt is made to create a map where more than one 
value would be associated with the same key.

Also see <<Map-invert>> and <<Prelude-Exception>>.

.Examples
[source,rascal-shell-error]
----
rascal>import Map;
ok
rascal>invertUnique(("apple": 1, "pear": 2, "orange": 3));
map[int, str]: (1:"apple",3:"orange",2:"pear")
----
Here is an examples that generates an exception:
[source,rascal-shell-error]
----
rascal>invertUnique(("apple": 1, "pear": 2, "orange": 1));
MultipleKey(1)
Call stack (most recent first):
	invertUnique(("pear":2,"orange":1,"apple":1), {}) at |std:///Map.rsc|(2804,742,<130,0>,<156,54>)
	main([]) at |test-modules:///ConsoleInput.rsc|(48,50,<4,15>,<4,65>)

ok
----



[[Map-isEmpty]]
## isEmpty

.Function 
`bool isEmpty(map[&K, &V] M)`


.Synopsis
Test whether a map is empty.

.Description
Returns `true` if map `M` is empty, and `false` otherwise.

.Examples
[source,rascal-shell]
----
rascal>import Map;
ok
rascal>isEmpty(());
bool: true
rascal>isEmpty(("apple": 1, "pear": 2, "orange": 3));
bool: false
----



[[Map-itoString]]
## itoString

.Function 
`str itoString(map[&K, &V] M)`


.Synopsis
Convert a map to a indented string.

.Examples
[source,rascal-shell]
----
rascal>import Map;
ok
rascal>itoString(("apple": 1, "pear": 2, "orange": 3));
str: "(\"pear\":2,\"orange\":3,\"apple\":1)"
----



[[Map-mapper]]
## mapper

.Function 
`map[&K, &V] mapper(map[&K, &V] M, &L (&K) F, &W (&V) G)`


.Synopsis
Apply a function to all (key, value) pairs in a map.

.Description
Apply the functions `F` and `G` to each key/value pair in a map and return the transformed map.

.Examples
[source,rascal-shell]
----
rascal>import Map;
ok
rascal>str prefix(str s) { return "X" + s; }
ok
rascal>int incr(int x) { return x + 1; }
ok
rascal>mapper(("apple": 1, "pear": 2, "orange": 3), prefix, incr);
map[str, int]: ("Xapple":2,"Xorange":4,"Xpear":3)
----



[[Map-range]]
## range

.Function 
`set[&V] range(map[&K, &V] M)`


.Synopsis
The range (set of values that correspond to its keys) of a map.

.Description
Returns the range (set of values) of map `M`.

.Examples
[source,rascal-shell]
----
rascal>import Map;
ok
rascal>range(("apple": 1, "pear": 2));
set[int]: {1,2}
----



[[Map-rangeR]]
## rangeR

.Function 
`map[&K, &V] rangeR(map[&K, &V] M, set[&V] S)`


.Synopsis
Map restricted to certain values in (key,values) pairs.

.Description
Returns the map restricted to pairs with values in `S`.

.Examples
[source,rascal-shell]
----
rascal>import Map;
ok
rascal>rangeR(("apple": 1, "pear": 2, "orange": 3), {2, 3});
map[str, int]: ("pear":2,"orange":3)
----



[[Map-rangeX]]
## rangeX

.Function 
`map[&K, &V] rangeX(map[&K, &V] M, set[&V] S)`


.Synopsis
Map with certain values in (key,value) pairs excluded.

.Description
Returns the map restricted to pairs with values not in `S`.

.Examples
[source,rascal-shell]
----
rascal>import Map;
ok
rascal>rangeX(("apple": 1, "pear": 2, "orange": 3), {2, 3});
map[str, int]: ("apple":1)
----



[[Map-size]]
## size

.Function 
`int size(map[&K, &V] M)`


.Synopsis
Number of (key, value) pairs in a map.

.Description
Returns the number of pairs in map `M`.

.Examples
[source,rascal-shell]
----
rascal>import Map;
ok
rascal>size(("apple": 1, "pear": 2, "orange": 3));
int: 3
----



[[Map-toList]]
## toList

.Function 
`list[tuple[&K, &V]] toList(map[&K, &V] M)`


.Synopsis
Convert a map to a list of tuples.

.Examples
[source,rascal-shell]
----
rascal>import Map;
ok
rascal>toList(("apple": 1, "pear": 2, "orange": 3));
lrel[str,int]: [
  <"apple",1>,
  <"orange",3>,
  <"pear",2>
]
----



[[Map-toRel]]
## toRel

.Function 
* `rel[&K,&V] toRel(map[&K,set[&V]] M)`
          * `rel[&K,&V] toRel(map[&K,list[&V]] M)`
          * `default rel[&K, &V] toRel(map[&K, &V] M)`
          


.Synopsis
Convert a map to a relation.

.Examples
[source,rascal-shell]
----
rascal>import Map;
ok
rascal>toRel(("apple": 1, "pear": 2, "orange": 3));
rel[str,int]: {
  <"apple",1>,
  <"pear",2>,
  <"orange",3>
}
----



[[Map-toString]]
## toString

.Function 
`str toString(map[&K, &V] M)`


.Synopsis
Convert a map to a string.

.Examples
[source,rascal-shell]
----
rascal>import Map;
ok
rascal>toString(("apple": 1, "pear": 2, "orange": 3));
str: "(\"pear\":2,\"orange\":3,\"apple\":1)"
----



:leveloffset: +1

:leveloffset: -1