
[[Func-Eval2]]
# Eval2
:concept: Languages/Func/Eval2

.Synopsis


.Syntax

.Types

.Function

.Description
Interpreter Eval2 supports the following features of Func: 


|====
| Feature              | Eval2

| function declaration | y
| integer constant     | y
| variable             | y
| arithmetic operators | y
| comparison operators | y
| call                 | y
| if                   | y
| let                  | y
| __sequence__         | y
| __assignment__       | y
| address operator     |
| dereference operator |
|====



The main additions are local side effects and the sequence operator.

.Examples

[source,rascal]
----
include::{LibDir}demo/lang/Func/Eval2.rsc[tags=module]
----

                
<1> The alias `Result` is introduced: a pair of an environment and an integer value.
    All evaluator functions are changed from returning an integer (the result of evaluation) to
   `Result` (the result of evaluation _and_ the local side effects).
<2> The effect of this change can be seen in all functions. For instance, when evaluating
    multiplication, the environment produced by the left operand ahs to be passed as 
    argument to the right operand of the multiplication. This is needed, to propagate any side effects
    caused by the left operand to propagate to the right one.
<3> Assignment is implemented.
<4>  Sequencing is implemented. Observe that that the value of the left operand is ignored and that
  the value of the right operand is returned.


We apply `eval2` to example `F2`:
[source,rascal]
----
include::{LibDir}demo/lang/Func/programs/F2.func[]
----

                
Let's try this.
[source,rascal-shell]
----
rascal>import demo::lang::Func::Load;
ok
rascal>import demo::lang::Func::Eval2;
rascal2rvm: Parsing and checking |std:///demo/lang/Func/Eval2.rsc|
rascal2rvm: Compiling |std:///demo/lang/Func/Eval2.rsc|
r2mu: entering ... demo::lang::Func::Eval2
mu2rvm: Compiling module demo::lang::Func::Eval2
Compiling |std:///demo/lang/Func/Eval2.rsc|: check: 29, compile: 1372, total: 1401 ms
compile: Writing RVMModule |compressed+home:///bin-console/demo/lang/Func/Eval2.rvm.gz|
Removing |compressed+home:///bin-console/ConsoleInput_imports.rvm.gz|
ok
rascal>import demo::lang::Func::programs::F2;
rascal2rvm: Parsing and checking |std:///demo/lang/Func/programs/F2.rsc|
rascal2rvm: Compiling |std:///demo/lang/Func/programs/F2.rsc|
r2mu: entering ... demo::lang::Func::programs::F2
mu2rvm: Compiling module demo::lang::Func::programs::F2
Compiling |std:///demo/lang/Func/programs/F2.rsc|: check: 3, compile: 9, total: 12 ms
compile: Writing RVMModule |compressed+home:///bin-console/demo/lang/Func/programs/F2.rvm.gz|
Removing |compressed+home:///bin-console/ConsoleInput_imports.rvm.gz|
ok
rascal>eval2("fact", [10], load(F2));
tuple[map[str, int],int]: <("n":3628800),3628800>
----

.Benefits

.Pitfalls


:leveloffset: +1

:leveloffset: -1