
[[m3-Core]]


[[m3-Core]]
# Core
:concept: lang/java/m3/Core
.Usage
`import lang::java::m3::Core;`


.Synopsis
extends the M3 [$analysis/m3/Core] with Java specific concepts such as inheritance and overriding.

.Description

For a quick start, go find <<createM3FromEclipseProject>>.

[[Core-Language]]
## Language
.Types
[source,rascal]
----
data Language (str version="") 
      = java()
      ;

----



[[Core-composeJavaM3]]
## composeJavaM3

.Function 
`M3 composeJavaM3(loc id, set[M3] models)`



[[Core-link]]
## link

.Function 
`M3 link(M3 projectModel, set[M3] libraryModels)`



[[Core-createM3FromFile]]
## createM3FromFile

.Function 
`M3 createM3FromFile(loc file, bool errorRecovery = false, list[loc] sourcePath = [], list[loc] classPath = [], str javaVersion = "1.7")`



[[Core-createM3sFromFiles]]
## createM3sFromFiles

.Function 
`set[M3] createM3sFromFiles(set[loc] files, bool errorRecovery = false, list[loc] sourcePath = [], list[loc] classPath = [], str javaVersion = "1.7")`



[[Core-createM3FromFiles]]
## createM3FromFiles

.Function 
`M3 createM3FromFiles(loc projectName, set[loc] files, bool errorRecovery = false, list[loc] sourcePath = [], list[loc] classPath = [], str javaVersion = "1.7")`



[[Core-createM3sAndAstsFromFiles]]
## createM3sAndAstsFromFiles

.Function 
`tuple[set[M3], set[Declaration]] createM3sAndAstsFromFiles(set[loc] files, bool errorRecovery = false, list[loc] sourcePath = [], list[loc] classPath = [], str javaVersion = "1.7")`



[[Core-createM3FromString]]
## createM3FromString

.Function 
`M3 createM3FromString(loc fileName, str contents, bool errorRecovery = false, list[loc] sourcePath = [], list[loc] classPath = [], str javaVersion = "1.7")`



[[Core-createM3FromJarClass]]
## createM3FromJarClass

.Function 
`M3 createM3FromJarClass(loc jarClass)`



[[Core-createM3FromDirectory]]
## createM3FromDirectory

.Function 
`M3 createM3FromDirectory(loc project, bool errorRecovery = false, str javaVersion = "1.7")`

.Synopsis
globs for jars, class files and java files in a directory and tries to compile all source files into an [$analysis/m3] model

[[Core-createM3FromJar]]
## createM3FromJar

.Function 
`M3 createM3FromJar(loc jarFile)`



[[Core-classPathToStr]]
## classPathToStr

.Function 
`str classPathToStr(loc jarClass)`



[[Core-isCompilationUnit]]
## isCompilationUnit

.Function 
`bool isCompilationUnit(loc entity)`



[[Core-isPackage]]
## isPackage

.Function 
`bool isPackage(loc entity)`



[[Core-isClass]]
## isClass

.Function 
`bool isClass(loc entity)`



[[Core-isConstructor]]
## isConstructor

.Function 
`bool isConstructor(loc entity)`



[[Core-isMethod]]
## isMethod

.Function 
`bool isMethod(loc entity)`



[[Core-isParameter]]
## isParameter

.Function 
`bool isParameter(loc entity)`



[[Core-isVariable]]
## isVariable

.Function 
`bool isVariable(loc entity)`



[[Core-isField]]
## isField

.Function 
`bool isField(loc entity)`



[[Core-isInterface]]
## isInterface

.Function 
`bool isInterface(loc entity)`



[[Core-isEnum]]
## isEnum

.Function 
`bool isEnum(loc entity)`



[[Core-files]]
## files

.Function 
`set[loc] files(rel[loc, loc] containment)`



[[Core-declaredMethods]]
## declaredMethods

.Function 
`rel[loc, loc] declaredMethods(M3 m, set[Modifier] checkModifiers = {})`



[[Core-declaredFields]]
## declaredFields

.Function 
`rel[loc, loc] declaredFields(M3 m, set[Modifier] checkModifiers = {})`



[[Core-declaredFieldsX]]
## declaredFieldsX

.Function 
`rel[loc, loc] declaredFieldsX(M3 m, set[Modifier] checkModifiers = {})`



[[Core-declaredTopTypes]]
## declaredTopTypes

.Function 
`rel[loc, loc] declaredTopTypes(M3 m)`



[[Core-declaredSubTypes]]
## declaredSubTypes

.Function 
`rel[loc, loc] declaredSubTypes(M3 m)`



[[Core-classes]]
## classes

.Function 
`set[loc] classes(M3 m)`



[[Core-interfaces]]
## interfaces

.Function 
`set[loc] interfaces(M3 m)`



[[Core-packages]]
## packages

.Function 
`set[loc] packages(M3 m)`



[[Core-variables]]
## variables

.Function 
`set[loc] variables(M3 m)`



[[Core-parameters]]
## parameters

.Function 
`set[loc] parameters(M3 m)`



[[Core-fields]]
## fields

.Function 
`set[loc] fields(M3 m)`



[[Core-methods]]
## methods

.Function 
`set[loc] methods(M3 m)`



[[Core-constructors]]
## constructors

.Function 
`set[loc] constructors(M3 m)`



[[Core-enums]]
## enums

.Function 
`set[loc] enums(M3 m)`



[[Core-elements]]
## elements

.Function 
`set[loc] elements(M3 m, loc parent)`



[[Core-fields]]
## fields

.Function 
`set[loc] fields(M3 m, loc class)`



[[Core-methods]]
## methods

.Function 
`set[loc] methods(M3 m, loc class)`



[[Core-constructors]]
## constructors

.Function 
`set[loc] constructors(M3 m, loc class)`



[[Core-nestedClasses]]
## nestedClasses

.Function 
`set[loc] nestedClasses(M3 m, loc class)`



:leveloffset: +1
include::typeDependency/typeDependency.adoc[typeDependency]


:leveloffset: -1