
[[Values-List]]
# List
:concept: Expressions/Values/List

.Synopsis
List values.

.Syntax
`[ _Exp_~1~, _Exp_~2~, ... ]`

.Types

//

[cols="20,20,20,40"]
|====
|  `_Exp~1~_` |  `_Exp~2~_` |  ...  |  `[ _Exp~1~_, _Exp~2~_, ... ]`   

| `_T~1~_`    | `_T~2~_`    |  ...  |  `list[lub(_T~1~_, _T~2~_, ... )]` 
|====

.Usage

.Function

.Description
A list is an ordered sequence of values and has the following properties:

*  All elements have the same static type.
*  The order of the elements matters.
*  A list may contain an element more than once.


The type of a list has the form `list[_T_]`,
where `_T_` is an arbitrary type.

When a value or variable of type list occurs inside a list, that list value is inserted as list element.
To achieve _splicing_ of these elements, i.e., the insertion of the elements of the list value rather than the whole list,
it has to be prefixed by the splice operator `*`.

The following operators are provided on list:


There are also link:{Libraries}#Prelude-List[library functions] available for List.

.Examples
[source,rascal-shell]
----
rascal>[1, 2, 3];
list[int]: [1,2,3]
rascal>[<1,10>, <2,20>, <3,30>];
lrel[int,int]: [
  <1,10>,
  <2,20>,
  <3,30>
]
rascal>[1, "b", 3];
list[value]: [1,"b",3]
rascal>[<"a",10>, <"b",20>, <"c",30>];
lrel[str,int]: [
  <"a",10>,
  <"b",20>,
  <"c",30>
]
rascal>[["a", "b"], ["c", "d", "e"]];
list[list[str]]: [
  ["a","b"],
  ["c","d","e"]
]
----
List splicing works as follows: by prefixing `L` by the splice operator, its elements are included as elements in the enclosing list:
[source,rascal-shell]
----
rascal>L = [1, 2, 3];
list[int]: [1,2,3]
rascal>[10, L, 20];
list[value]: [
  10,
  [1,2,3],
  20
]
rascal>[10, *L, 20];
list[int]: [10,1,2,3,20]
----

.Benefits

.Pitfalls


:leveloffset: +1
include::Append/Append.adoc[Append]

include::Comprehension/Comprehension.adoc[Comprehension]

include::Concatenation/Concatenation.adoc[Concatenation]

include::Difference/Difference.adoc[Difference]

include::Equal/Equal.adoc[Equal]

include::Insert/Insert.adoc[Insert]

include::Intersection/Intersection.adoc[Intersection]

include::NotEqual/NotEqual.adoc[NotEqual]

include::Product/Product.adoc[Product]

include::Slice/Slice.adoc[Slice]

include::Splice/Splice.adoc[Splice]

include::StrictSubList/StrictSubList.adoc[StrictSubList]

include::StrictSuperList/StrictSuperList.adoc[StrictSuperList]

include::SubList/SubList.adoc[SubList]

include::Subscription/Subscription.adoc[Subscription]

include::SuperList/SuperList.adoc[SuperList]

include::in/in.adoc[in]

include::notin/notin.adoc[notin]

include::CartesianProduct/CartesianProduct.adoc[CartesianProduct]

include::Composition/Composition.adoc[Composition]

include::FieldSelection/FieldSelection.adoc[FieldSelection]

include::Join/Join.adoc[Join]

include::ReflexiveTransitiveClosure/ReflexiveTransitiveClosure.adoc[ReflexiveTransitiveClosure]

include::Subscription/Subscription.adoc[Subscription]

include::TransitiveClosure/TransitiveClosure.adoc[TransitiveClosure]


:leveloffset: -1