
[[Prelude-String]]


[[Prelude-String]]
# String
:concept: Prelude/String
.Usage
`import String;`


.Synopsis
Library functions for strings.

.Description

For operators on strings see link:{RascalLang}#Values-String[String] in the Rascal Language Reference.

The following functions are defined for strings:


[[String-center]]
## center

.Function 
* `str center(str s, int n)`
          * `str center(str s, int n, str pad)`
          

.Synopsis
Center a string in given space.

.Description

*  Center string `s` in string of length `n` using spaces.
*  Center string `s` in string of length `n` using `pad` as padding character.

.Examples
[source,rascal-shell]
----
rascal>import String;
ok
rascal>center("abc", 10);
str: "   abc    "
rascal>center("abc", 10, "x");
str: "xxxabcxxxx"
----

[[String-charAt]]
## charAt

.Function 
`int charAt(str s, int i) throws IndexOutOfBounds(str msg)`

.Synopsis
Return character in a string by its index position.

.Description
Return the character at position `i` in string `s` as integer character code.
Also see <<String-stringChar>> that converts character codes back to string.

.Examples
[source,rascal-shell]
----
rascal>import String;
ok
rascal>charAt("abc", 0);
int: 97
rascal>stringChar(charAt("abc", 0));
str: "a"
----

[[String-chars]]
## chars

.Function 
`list[int] chars(str s)`

.Synopsis
Return characters of a string.
.Description
Return a list of the characters of `s` as integer character codes.
Also see <<String-stringChars>> that converts character codes back to string.

.Examples
[source,rascal-shell]
----
rascal>import String;
ok
rascal>chars("abc");
list[int]: [97,98,99]
rascal>stringChars(chars("abc")) == "abc";
bool: true
----

[[String-contains]]
## contains

.Function 
`bool contains(str input, str find)`

.Synopsis
Check that a string contains another string.

.Description
Check whether the string `find` occurs as substring in the string `subject`.

.Examples
[source,rascal-shell]
----
rascal>import String;
ok
rascal>contains("abracadabra", "bra");
bool: true
rascal>contains("abracadabra", "e");
bool: false
----

[[String-endsWith]]
## endsWith

.Function 
`bool endsWith(str subject, str suffix)`

.Synopsis
Check whether a string ends with a given substring.

.Description
Yields `true` if string `subject` ends with the string `suffix`.

.Examples
[source,rascal-shell]
----
rascal>import String;
ok
rascal>endsWith("Hello.rsc", ".rsc");
bool: true
----

[[String-escape]]
## escape

.Function 
`str escape(str subject, map[str,str] mapping)`

.Synopsis
Replace single characters in a string.

.Description
Return a copy of `subject` in which each single character key in replacements
has been replaced by its associated value.

.Examples
[source,rascal-shell]
----
rascal>import String;
ok
rascal>import IO;
ok
rascal>escape("abracadabra", ("a" : "AA", "c" : "C"));
str: "AAbrAACAAdAAbrAA"
rascal>L = escape("\"Good Morning\", he said", ("\"": "\\\""));
str: "\\\"Good Morning\\\", he said"
rascal>println(L);
\"Good Morning\", he said
ok
----

[[String-findAll]]
## findAll

.Function 
`list[int] findAll(str subject, str find)`

.Synopsis
Find all occurrences of a string in another string.

.Description
Find all occurrences of string `find` in string `subject`.
The result is a (possible empty) list of positions where `find` matches.

See also <<findFirst>> and <<findLast>>.

.Examples
[source,rascal-shell]
----
rascal>import String;
ok
rascal>findAll("abracadabra", "a");
list[int]: [0,3,5,7,10]
rascal>findAll("abracadabra", "bra");
list[int]: [1,8]
rascal>findAll("abracadabra", "e");
list[void]: []
----

[[String-findFirst]]
## findFirst

.Function 
`int findFirst(str subject, str find)`

.Synopsis
Find the first occurrence of a string in another string.

.Description
Find the first occurrence of string `find` in string `subject`.
The result is either a position in `subject` or `-1` when `find` is not found.

Also see <<findAll>> and <<findLast>>.

.Examples
[source,rascal-shell]
----
rascal>import String;
ok
rascal>findFirst("abracadabra", "a");
int: 0
rascal>findFirst("abracadabra", "bra");
int: 1
rascal>findFirst("abracadabra", "e");
int: -1
----

[[String-findLast]]
## findLast

.Function 
`int findLast(str subject, str find)`

.Synopsis
Find the last occurrence of a string in another string.

.Description
Find the last occurrence of string `find` in string `subject`.
The result is either a position in `subject` or `-1` when `find` is not found.

Also see <<findAll>> and <<findFirst>>.

.Examples
[source,rascal-shell]
----
rascal>import String;
ok
rascal>findLast("abracadabra", "a");
int: 10
rascal>findLast("abracadabra", "bra");
int: 8
rascal>findLast("abracadabra", "e");
int: -1
----

[[String-isEmpty]]
## isEmpty

.Function 
`bool isEmpty(str s)`

.Synopsis
Check whether a string is empty.

.Description
Returns `true` if string `s` is empty.

.Examples
[source,rascal-shell]
----
rascal>import String;
ok
rascal>isEmpty("");
bool: true
rascal>isEmpty("abc");
bool: false
----

[[String-left]]
## left

.Function 
* `str left(str s, int n)`
          * `str left(str s, int n, str pad)`
          

.Synopsis
Left alignment of string in given space.

.Description

*  Left align string `s` in string of length `n` using spaces.
*  Left align string `s` in string of length `n` using `pad` as pad character.

.Examples
[source,rascal-shell]
----
rascal>import String;
ok
rascal>left("abc", 10);
str: "abc       "
rascal>left("abc", 10, "x");
str: "abcxxxxxxx"
----

[[String-replaceAll]]
## replaceAll

.Function 
`str replaceAll(str subject, str find, str replacement)`

.Synopsis
Replace all occurrences of a string in another string.

.Description
Return a copy of `subject` in which all occurrences of `find` (if any) have been replaced by `replacement`.
Also see <<replaceFirst>> and <<replaceLast>>.

.Examples
[source,rascal-shell]
----
rascal>import String;
ok
rascal>replaceAll("abracadabra", "a", "A");
str: "AbrAcAdAbrA"
rascal>replaceAll("abracadabra", "ra", "RARA");
str: "abRARAcadabRARA"
rascal>replaceAll("abracadabra", "cra", "CRA");
str: "abracadabra"
----

.Pitfalls
Note that `find` is a string (as opposed to, for instance, a regular expression in Java).

[[String-replaceFirst]]
## replaceFirst

.Function 
`str replaceFirst(str subject, str find, str replacement)`

.Synopsis
Replace the first occurrence of a string in another string.

.Description
Return a copy of `subject` in which the first occurrence of `find` (if it exists) has been replaced by `replacement`.
Also see <<replaceAll>> and <<replaceLast>>.

.Examples
[source,rascal-shell]
----
rascal>import String;
ok
rascal>replaceFirst("abracadabra", "a", "A");
str: "Abracadabra"
rascal>replaceFirst("abracadabra", "ra", "RARA");
str: "abRARAcadabra"
rascal>replaceFirst("abracadabra", "cra", "CRA");
str: "abracadabra"
----

.Pitfalls
Note that `find` is a string (as opposed to, for instance, a regular expression in Java).

[[String-replaceLast]]
## replaceLast

.Function 
`str replaceLast(str subject, str find, str replacement)`

.Synopsis
Replace the last occurrence of a string in another string.

.Description
Return a copy of `subject` in which the last occurrence of `find` (if it exists) has been replaced by `replacement`.
Also see <<replaceFirst>> and <<replaceLast>>.

.Examples
[source,rascal-shell]
----
rascal>import String;
ok
rascal>replaceLast("abracadabra", "a", "A");
str: "abracadabrA"
rascal>replaceLast("abracadabra", "ra", "RARA");
str: "abracadabRARA"
rascal>replaceLast("abracadabra", "cra", "CRA");
str: "abracadabra"
----

.Pitfalls
Note that `find` is a string (as opposed to, for instance, a regular expression in Java).

[[String-reverse]]
## reverse

.Function 
`str reverse(str s)`

.Synopsis
Return a string with all characters in reverse order.

.Description
Returns string with all characters of string `s` in reverse order.

.Examples
[source,rascal-shell]
----
rascal>import String;
ok
rascal>reverse("abc");
str: "cba"
----

[[String-right]]
## right

.Function 
* `str right(str s, int n)`
          * `str right(str s, int n, str pad)`
          

.Synopsis
Right alignment of a string value in a given space.

.Description

*  Right align string `s` in string of length `n` using spaces.
*  Right align string `s` in string of length `n` using `pad` as pad character.

.Examples
[source,rascal-shell]
----
rascal>import String;
ok
rascal>right("abc", 10);
str: "       abc"
rascal>right("abc", 10, "x");
str: "xxxxxxxabc"
----

[[String-size]]
## size

.Function 
`int size(str s)`

.Synopsis
Determine length of a string value.

.Description
Returns the length (number of characters) in string `s`.

.Examples
[source,rascal-shell]
----
rascal>import String;
ok
rascal>size("abc");
int: 3
rascal>size("");
int: 0
----

[[String-startsWith]]
## startsWith

.Function 
`bool startsWith(str subject, str prefix)`

.Synopsis
Check whether a string starts with a given prefix.

.Description
Yields `true` if string `subject` starts with the string `prefix`.

.Examples
[source,rascal-shell]
----
rascal>import String;
ok
rascal>startsWith("Hello.rsc", "Hell");
bool: true
----

[[String-stringChar]]
## stringChar

.Function 
`str stringChar(int char) throws IllegalArgument(int character)`

.Synopsis
Convert a character code into a string.

[[String-stringChars]]
## stringChars

.Function 
`str stringChars(list[int] chars) throws IllegalArgument(int character)`

.Synopsis
Convert a list of character codes into a string.

[[String-isValidCharacter]]
## isValidCharacter

.Function 
`bool isValidCharacter(int ch)`

.Synopsis
Check that a given integer value is a valid Unicode code point.

[[String-substring]]
## substring

.Function 
* `str substring(str s, int begin)`
          * `str substring(str s, int begin, int end)`
          

.Synopsis
Extract a substring from a string value.

.Description

*  Yields substring of string `s` from index `begin` to the end of the string.
*  Yields substring of string `s` from index `begin` to (but not including) index `end`.

.Examples
[source,rascal-shell]
----
rascal>import String;
ok
rascal>substring("abcdef", 2);
str: "cdef"
rascal>substring("abcdef", 2, 4);
str: "cd"
----

[[String-toInt]]
## toInt

.Function 
* `int toInt(str s) throws IllegalArgument`
          * `int toInt(str s, int r) throws IllegalArgument`
          

.Synopsis
Convert a string value to integer.

.Description

*  Converts string `s` to integer. 
*  Convert string `s` to integer using radix `r`.


Throws `IllegalArgument` when `s` cannot be converted.

.Examples
[source,rascal-shell-error]
----
rascal>import String;
ok
rascal>toInt("11");
int: 11
rascal>toInt("11", 8);
int: 9
----
Now try an erroneous argument:
[source,rascal-shell-error]
----
rascal>toInt("abc");
IllegalArgument("abc","For input string: \"abc\"")
Call stack (most recent first):
	toInt("abc", {}) at |std:///String.rsc|(10208,490,<472,0>,<498,52>)
	main([]) at |test-modules:///ConsoleInput.rsc|(51,12,<4,15>,<4,27>)

ok
----

[[String-toLowerCase]]
## toLowerCase

.Function 
`str toLowerCase(str s)`

.Synopsis
Convert the characters in a string value to lower case.

.Description
Convert all characters in string `s` to lowercase. Also see <<toUpperCase>>.

.Examples
[source,rascal-shell]
----
rascal>import String;
ok
rascal>toLowerCase("AaBbCc123");
str: "aabbcc123"
----

[[String-toReal]]
## toReal

.Function 
`real toReal(str s)`

.Synopsis
Convert a string value to real.

.Description
Converts string `s` to a real. Throws `IllegalArgument` when `s` cannot be converted.

.Examples
[source,rascal-shell-error]
----
rascal>import String;
ok
rascal>toReal("2.5e-3");
real: 0.0025
rascal>toReal("123");
real: 123.
rascal>toReal("abc");
IllegalArgument()
Call stack (most recent first):
	toReal("abc", {}) at |std:///String.rsc|(11132,335,<521,0>,<538,31>)
	main([]) at |test-modules:///ConsoleInput.rsc|(51,13,<4,15>,<4,28>)

ok
----

[[String-toUpperCase]]
## toUpperCase

.Function 
`str toUpperCase(str s)`

.Synopsis
Convert the characters in a string value to upper case.

.Description
Converts all characters in string `s` to upper case.

Also see <<toLowerCase>>.

.Examples
[source,rascal-shell]
----
rascal>import String;
ok
rascal>toUpperCase("AaBbCc123");
str: "AABBCC123"
----

[[String-trim]]
## trim

.Function 
`str trim(str s)`

.Synopsis
Returns string with leading and trailing whitespace removed.

.Examples
[source,rascal-shell]
----
rascal>import String;
ok
rascal>trim("  jelly
>>>>>>>beans  ");
str: "jelly\nbeans"
----

[[String-squeeze]]
## squeeze

.Function 
`str squeeze(str src, str charSet)`

.Synopsis
Squeeze repeated occurrences of characters.
.Description
Squeeze repeated occurrences in `src` of characters in `charSet` removed.
See http://commons.apache.org/lang/api-2.6/index.html?org/apache/commons/lang/text/package-summary.html[Apache]
for the allowed syntax in `charSet`.

.Examples
[source,rascal-shell]
----
rascal>import String;
ok
rascal>squeeze("hello", "el");
str: "helo"
----

[[String-split]]
## split

.Function 
`list[str] split(str sep, str src)`

.Synopsis
Split a string into a list of strings based on a literal separator.

[[String-capitalize]]
## capitalize

.Function 
`str capitalize(str src)`



[[String-uncapitalize]]
## uncapitalize

.Function 
`str uncapitalize(str src)`



[[String-toBase64]]
## toBase64

.Function 
`str toBase64(str src)`



[[String-fromBase64]]
## fromBase64

.Function 
`str fromBase64(str src)`



[[String-wrap]]
## wrap

.Function 
`str wrap(str src, int wrapLength)`

.Synopsis
Word wrap a string to fit in a certain width.

.Description
Inserts newlines in a string in order to fit the string in a certain width. It only breaks on spaces (' ').

[[String-format]]
## format

.Function 
`str format(str s, str dir, int n, str pad)`



[[String-rexpMatch]]
## rexpMatch

.Function 
`bool rexpMatch(str s, str re)`

.Synopsis
Determine if a string matches the given (Java-syntax) regular expression.

[[String-toLocation]]
## toLocation

.Function 
`loc toLocation(str s)`

.Synopsis
Convert a string value to a (source code) location.

.Description

*  Converts string `s` to a location.
*  If the scheme is not provided, it is assumed to be `cwd`.

.Examples
[source,rascal-shell]
----
rascal>import String;
ok
rascal>toLocation("http://grammarware.net");
loc: |http://grammarware.net|
rascal>toLocation("document.xml");
loc: |cwd:///document.xml|
----

[[String-substitute]]
## substitute

.Function 
`str substitute(str src, map[loc,str] s)`

.Synopsis
Substitute substrings in a string based on a substitution map from location to string.

.Examples
[source,rascal-shell]
----
rascal>import String;
ok
rascal>substitute("abc", (|stdin://|(1,1): "d"))
[error] Expected 4 arguments: int, int, tuple[int,int], and tuple[int,int] IN '|stdin://|(1,1)'
----

:leveloffset: +1

:leveloffset: -1