[[Func-Parse]]
# Parse
:concept: Languages/Func/Parse

.Synopsis
Parse a Func program from a string or a file.

.Syntax

.Types

.Function

.Description
Parsing uses the syntax rules for a given start non-terminnal to parse a string and turn it into a parse tree.
The work horse is the link::{Rascal}#parse[] function that is available in the link::{Rascal}#Prelude-ParseTree[] library.

.Examples
Here is how to parse Func programs from a string or file:
[source,rascal]
----
include::{LibDir}demo/lang/Func/Parse.rsc[tags=module]
----

                
Let's try this on example `F0.func`:
[source,rascal]
----
include::{LibDir}demo/lang/Func/programs/F0.func[]
----

First, we try the version with a string argument:
[source,rascal-shell]
----
rascal>import demo::lang::Func::Parse;
ok
rascal>import demo::lang::Func::programs::F0;
ok
rascal>parse(F0);
Prog: (Prog) `fact(n) = [35mif[39m n <= 1 [35mthen[39m
             1 
          [35melse[39m 
             n * fact(n[35m-[39m1)
          [35mend[39m`
----
This must be defined as success: we get the original program and its parse tree back.
Next, we try the same from a file. We use the scheme `std` that refers to files that reside in the Rascal library.
See [$Rascal:Expressions/Values/Location] for further details on other schemes.
[source,rascal-shell]
----
rascal>parse(|std:///demo/lang/Func/programs/F0.func|);
Prog: (Prog) `fact(n) = [35mif[39m n <= 1 [35mthen[39m
             1 
          [35melse[39m 
             n * fact(n[35m-[39m1)
          [35mend[39m`
----

.Benefits

.Pitfalls


:leveloffset: +1

:leveloffset: -1