
[[Dynamic-IO]]
# IO
:concept: Dynamic/IO

.Synopsis
An input/output operation caused an error.

.Syntax

.Types

.Function
.Usage

.Description
This error can be generated for many reasons.

First there may be a problem in the link:{RascalLang}#Values-Location[location] that is used.
It maybe that the _schemes_ is not supported.
Examples of supported schemes include `http`, `file`, `home`, `std`, `rascal` and `project`.
It can also be the case that the _host_ that occurs in the location cannot be found.

Second, while trying to open the file things can go wrong like insufficient access rights

Finally, actual reading or writing can fail (device failure, device full, and the like).

Remedies:

*  Check for any errors in the location you are using.
*  Check that you are allowed to read or write the resource indicated by the location.
*  Catch `IO` using a link:{RascalLang}#Statements-TryCatch[try catch].

.Examples
Import the `IO` library and attempt to use a non-existing scheme:
[source,rascal-shell-error]
----
rascal>import IO;
ok
rascal>readFile(|myScheme:///example.rsc|);
IO("Unsupported scheme myScheme")
Call stack (most recent first):
	readFile(|myScheme:///example.rsc|, {}) at |std:///IO.rsc|(12600,1747,<540,0>,<576,43>)
	main([]) at |test-modules:///ConsoleInput.rsc|(47,35,<4,15>,<4,50>)

ok
----
We can catch this `IO` error. First import the Rascal exceptions (which are also included in `Prelude`):
[source,rascal-shell-error]
----
rascal>import Exception;
ok
rascal>try readFileLines(|myScheme:///example.rsc|); catch IO(msg): println("This did not work: <msg>");
This did not work: Unsupported scheme myScheme
ok
----

.Benefits

.Pitfalls


:leveloffset: +1

:leveloffset: -1