
[[statistics-Descriptive]]


[[statistics-Descriptive]]
# Descriptive
:concept: analysis/statistics/Descriptive
.Usage
`import analysis::statistics::Descriptive;`


.Synopsis
Descriptive Statistics.

.Description
Provides the following univariate (single variable) statistics functions:



.Examples

[source,rascal-shell]
----
rascal>import analysis::statistics::Descriptive;
ok
rascal>D = [67, 88, 55, 92.5, 102, 51];
list[num]: [67,88,55,92.5,102,51]
rascal>mn = min(D);
int: 51
rascal>mx = max(D);
int: 102
rascal>range = mx - mn;
int: 51
rascal>midrange =  mn + range/2;
int: 76
rascal>sum(D);
real: 455.5
rascal>mean(D);
real: 75.91666667
rascal>geometricMean(D);
real: 73.3734107237
rascal>standardDeviation(D);
real: 21.1622698845
rascal>variance(D);
real: 447.841666666666666666666666666
rascal>percentile(D,25);
int: 55
rascal>percentile(D,50);
int: 67
rascal>percentile(D,75);
real: 92.5
----

[[Descriptive-geometricMean]]
## geometricMean

.Function 
* `real geometricMean(list[num] l:[])`
          * `default real geometricMean([num hd, *num tl])`
          



[[Descriptive-kurtosis]]
## kurtosis

.Function 
`real kurtosis(list[num] values)`

.Synopsis
Kurtosis of data values.

.Description

Computes the http://en.wikipedia.org/wiki/Kurtosis[kurtosis] of the given data values.
Kurtosis is a measure of the "peakedness" of a distribution.

[[Descriptive-kurtosisExcess]]
## kurtosisExcess

.Function 
`real kurtosisExcess(list[num] values)`

.Synopsis
Kurtosis excess of data values.

.Description

Computes the http://en.wikipedia.org/wiki/Kurtosis[kurtosis excess] of the given data values.
Kurtosis excess is a measure of the "peakedness" of a distribution corrected such that a normal distribution will be 0.

[[Descriptive-max]]
## max

.Function 
`(&T <: num) max(list[&T <: num] nums) throws EmptyList`

.Synopsis
Largest data value.

[[Descriptive-mean]]
## mean

.Function 
* `real mean(list[&T<:num] l:[])`
          * `default real mean(list[num] nums)`
          



[[Descriptive-median]]
## median

.Function 
* `real median(list[num] l:[])`
          * `default real median(list[num] nums)`
          



[[Descriptive-middle]]
## middle

.Function 
`list[&T] middle(list[&T] nums)`



[[Descriptive-min]]
## min

.Function 
`(&T <: num) min(list[&T <: num] nums) throws EmptyList`

.Synopsis
Smallest data value.

[[Descriptive-percentile]]
## percentile

.Function 
`&T <: num percentile(list[&T <: num] nums, num p)`

.Synopsis
Percentile of data values.

.Description

Returns the `p`th http://en.wikipedia.org/wiki/Percentile[percentile] of the data values.
 0 < `p` <= 100 should hold.

[[Descriptive-variance]]
## variance

.Function 
* `num variance(list[num] l:[])`
          * `num variance([num hd, *num tl])`
          



[[Descriptive-skewness]]
## skewness

.Function 
* `real skewness(list[num] l:[])`
          * `default real skewness(list[num] values)`
          



[[Descriptive-standardDeviation]]
## standardDeviation

.Function 
`real standardDeviation(list[num] values)`

.Synopsis
Standard deviation of data values.

.Description
Computes the http://en.wikipedia.org/wiki/Standard_deviation[standard deviation]
of the data values. It shows how much variation exists from the average (mean, or expected value).

[[Descriptive-sum]]
## sum

.Function 
* `(&T <:num) sum(list[(&T <:num)] _:[])`
          * `default (&T <:num) sum([(&T <: num) hd, *(&T <: num) tl])`
          



[[Descriptive-sumsq]]
## sumsq

.Function 
`(&T <:num) sumsq(list[&T <:num] values)`

.Synopsis
Sum of the squares of data values.

[[Descriptive-centralMoment]]
## centralMoment

.Function 
`real centralMoment(list[num] nums, int order = 1)`

Calculate the k-th central moment

[[Descriptive-moment]]
## moment

.Function 
`real moment(list[num] nums, int order = 1)`

Calculate the k-th moment

[[Descriptive-size]]
## size

.Function 
`int size(list[&T] lst)`



[[Descriptive-tail]]
## tail

.Function 
`list[&T] tail(list[&T] lst) throws EmptyList`



[[Descriptive-head]]
## head

.Function 
`&T head(list[&T] lst) throws EmptyList`



[[Descriptive-sort]]
## sort

.Function 
* `list[&T] sort(list[&T] lst)`
          * `list[&T] sort(list[&T] l, bool (&T a, &T b) less)`
          



:leveloffset: +1

:leveloffset: -1