
[[Dynamic-ParseError]]
# ParseError
:concept: Dynamic/ParseError

.Synopsis
Parse of a syntactically incorrect string.

.Syntax

.Types

.Function
.Usage

.Description
This error is generated when during the execution of a Rascal program the
link:{Libraries}#ParseTree-parse[parse] function is applied to a syntactically incorrect input sentence.

Remedies:

*  Correct the input sentence.
*  Adapt the grammar so that it accepts the inpout sentence.
*  Catch the ParseError yourself, see link:{RascalLang}#Statements-TryCatch[try catch].


.Examples
[source,rascal-shell-error]
----
----
Define the Non-terminal `As` that accepts one or more letters `a`:
[source,rascal-shell-error]
----
rascal>import ParseTree;
ok
rascal>syntax As = "a"+;
ok
----
It parses a sentences of letters `a`:
[source,rascal-shell-error]
----
rascal>parse(#As, "aaaaaaaa");
As: (As) `[35ma[39m[35ma[39m[35ma[39m[35ma[39m[35ma[39m[35ma[39m[35ma[39m[35ma[39m`
----
But gives an error when parsing an input that it cannot accept:
[source,rascal-shell-error]
----
rascal>parse(#As, "aaaabaaa");
ParseError(|unknown:///|(4,1,<1,4>,<1,5>))
No call stack available

ok
----
We can also catch the ParseError. First import the Rascal exceptions (which are also included in Prelude) and IO:
[source,rascal-shell-error]
----
rascal>import Exception;
ok
rascal>import IO;
ok
rascal>try parse(#As, "aaaabaaa"); catch ParseError(e): println("Your input cannot be parsed: <e>");
Your input cannot be parsed: |unknown:///|(4,1,<1,4>,<1,5>)
ok
----


.Benefits

.Pitfalls


:leveloffset: +1

:leveloffset: -1