
[[Dynamic-ParseError]]
# ParseError
:concept: Dynamic/ParseError

.Synopsis
Parse of a syntactically incorrect string.

.Syntax

.Types

.Function
.Usage

.Description
This error is generated when during the execution of a Rascal program the
link:{Libraries}#ParseTree-parse[parse] function is applied to a syntactically incorrect input sentence.

Remedies:

*  Correct the input sentence.
*  Adapt the grammar so that it accepts the inpout sentence.
*  Catch the ParseError yourself, see link:{RascalLang}#Statements-TryCatch[try catch].


.Examples
[source,rascal-shell-error]
----
----
Define the Non-terminal `As` that accepts one or more letters `a`:
[source,rascal-shell-error]
----
rascal>import ParseTree;
rascal2rvm: Parsing and checking |std:///Message.rsc|
rascal2rvm: Compiling |std:///Message.rsc|
r2mu: entering ... Message
mu2rvm: Compiling module Message
Compiling |std:///Message.rsc|: check: 10, compile: 16, total: 26 ms
compile: Writing RVMModule |compressed+home:///bin-console/Message.rvm.gz|
rascal2rvm: Parsing and checking |std:///ParseTree.rsc|
rascal2rvm: Compiling |std:///ParseTree.rsc|
r2mu: entering ... ParseTree
rlib1 = Prelude, rlib2 = |std:///PreludeCompiled.class|
resolveLibOverriding org.rascalmpl.library.Prelude => org.rascalmpl.library.PreludeCompiled
mu2rvm: Compiling module ParseTree
Compiling |std:///ParseTree.rsc|: check: 93, compile: 882, total: 975 ms
compile: Writing RVMModule |compressed+home:///bin-console/ParseTree.rvm.gz|
rascal2rvm: Parsing and checking |std:///Type.rsc|
rascal2rvm: Compiling |std:///Type.rsc|
r2mu: entering ... Type
rlib1 = Type, rlib2 = |std:///TypeCompiled.class|
resolveLibOverriding org.rascalmpl.library.Type => org.rascalmpl.library.Type
mu2rvm: Compiling module Type
Compiling |std:///Type.rsc|: check: 272, compile: 6041, total: 6313 ms
compile: Writing RVMModule |compressed+home:///bin-console/Type.rvm.gz|
Removing |compressed+home:///bin-console/ConsoleInput_imports.rvm.gz|
ok
rascal>syntax As = "a"+;
ok
----
It parses a sentences of letters `a`:
[source,rascal-shell-error]
----
rascal>parse(#As, "aaaaaaaa");
As: (As) `[35ma[39m[35ma[39m[35ma[39m[35ma[39m[35ma[39m[35ma[39m[35ma[39m[35ma[39m`
----
But gives an error when parsing an input that it cannot accept:
[source,rascal-shell-error]
----
rascal>parse(#As, "aaaabaaa");
ParseError(|unknown:///|(4,1,<1,4>,<1,5>))
No call stack available

ok
----
We can also catch the ParseError. First import the Rascal exceptions (which are also included in Prelude) and IO:
[source,rascal-shell-error]
----
rascal>import Exception;
ok
rascal>import IO;
ok
rascal>try parse(#As, "aaaabaaa"); catch ParseError(e): println("Your input cannot be parsed: <e>");
Your input cannot be parsed: |unknown:///|(4,1,<1,4>,<1,5>)
ok
----


.Benefits

.Pitfalls


:leveloffset: +1

:leveloffset: -1